<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Unit;
use App\Models\Department;
use Illuminate\Support\Facades\DB;

/**
 * ProjectSeeder - بيانات تجريبية للمشاريع
 * 
 * ينشئ 25 مشروع متنوع بحالات وأنواع مختلفة
 */
class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('projects')->delete();
        
        $units = Unit::all();
        $departments = Department::all();
        
        if ($units->count() < 10 || $departments->count() < 15) {
            $this->command->error('⚠️ يجب تشغيل UnitSeeder و DepartmentSeeder أولاً');
            return;
        }

        $projects = [
            // مشاريع العباسي العقارية
            [
                'unit_id' => 1,
                'department_id' => 1,
                'code' => 'PRJ-001',
                'name' => 'مشروع أبراج العباسي السكنية',
                'name_en' => 'Al-Abbasi Residential Towers',
                'type' => 'real_estate',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-01-01',
                'planned_end_date' => '2026-12-31',
                'actual_end_date' => null,
                'budget' => 150000000.00,
                'actual_cost' => 45000000.00,
                'progress_percentage' => 30.00,
                'location' => 'حي النرجس، الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مشروع سكني فاخر يتكون من 4 أبراج بإجمالي 320 وحدة سكنية',
                'notes' => 'المشروع يسير حسب الخطة الزمنية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 1,
                'department_id' => 1,
                'code' => 'PRJ-002',
                'name' => 'مجمع العباسي التجاري',
                'name_en' => 'Al-Abbasi Commercial Complex',
                'type' => 'commercial',
                'status' => 'planning',
                'priority' => 'medium',
                'start_date' => '2025-03-01',
                'planned_end_date' => '2027-06-30',
                'actual_end_date' => null,
                'budget' => 200000000.00,
                'actual_cost' => 5000000.00,
                'progress_percentage' => 5.00,
                'location' => 'طريق الملك عبدالله، الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مجمع تجاري متكامل بمساحة 50,000 متر مربع',
                'notes' => 'في مرحلة التصاميم النهائية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 3, // فرع جدة
                'department_id' => 1,
                'code' => 'PRJ-003',
                'name' => 'منتجع البحر الأحمر',
                'name_en' => 'Red Sea Resort',
                'type' => 'hospitality',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2023-06-01',
                'planned_end_date' => '2025-12-31',
                'actual_end_date' => null,
                'budget' => 300000000.00,
                'actual_cost' => 180000000.00,
                'progress_percentage' => 60.00,
                'location' => 'شمال جدة، كورنيش البحر الأحمر',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'منتجع سياحي فاخر بسعة 200 غرفة ومرافق ترفيهية',
                'notes' => 'المشروع متقدم بشكل جيد',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 4, // فرع الدمام
                'department_id' => 1,
                'code' => 'PRJ-004',
                'name' => 'مدينة الفجر الصناعية',
                'name_en' => 'Al-Fajr Industrial City',
                'type' => 'industrial',
                'status' => 'completed',
                'priority' => 'high',
                'start_date' => '2020-01-01',
                'planned_end_date' => '2023-12-31',
                'actual_end_date' => '2023-11-15',
                'budget' => 500000000.00,
                'actual_cost' => 485000000.00,
                'progress_percentage' => 100.00,
                'location' => 'المنطقة الصناعية، الدمام',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مدينة صناعية متكاملة بمساحة 2 مليون متر مربع',
                'notes' => 'تم الانتهاء من المشروع بنجاح',
                'is_active' => false,
                'created_by' => 1,
            ],
            
            // مشاريع العباسي للتجارة
            [
                'unit_id' => 2,
                'department_id' => 5,
                'code' => 'PRJ-005',
                'name' => 'توسعة شبكة التوزيع',
                'name_en' => 'Distribution Network Expansion',
                'type' => 'infrastructure',
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => '2024-06-01',
                'planned_end_date' => '2025-06-30',
                'actual_end_date' => null,
                'budget' => 25000000.00,
                'actual_cost' => 12000000.00,
                'progress_percentage' => 48.00,
                'location' => 'مناطق متعددة',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'توسعة شبكة التوزيع لتغطية 15 مدينة جديدة',
                'notes' => 'تم افتتاح 7 مراكز توزيع حتى الآن',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 2,
                'department_id' => 6,
                'code' => 'PRJ-006',
                'name' => 'نظام إدارة المخزون الذكي',
                'name_en' => 'Smart Inventory Management System',
                'type' => 'technology',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-09-01',
                'planned_end_date' => '2025-03-31',
                'actual_end_date' => null,
                'budget' => 8000000.00,
                'actual_cost' => 4500000.00,
                'progress_percentage' => 56.00,
                'location' => 'جميع المستودعات',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'نظام متكامل لإدارة المخزون باستخدام تقنية RFID',
                'notes' => 'تم تركيب النظام في 8 مستودعات',
                'is_active' => true,
                'created_by' => 1,
            ],
            
            // مشاريع النور للاستشارات
            [
                'unit_id' => 5,
                'department_id' => 7,
                'code' => 'PRJ-007',
                'name' => 'دراسة جدوى مشروع الطاقة الشمسية',
                'name_en' => 'Solar Energy Project Feasibility Study',
                'type' => 'consulting',
                'status' => 'completed',
                'priority' => 'medium',
                'start_date' => '2024-01-15',
                'planned_end_date' => '2024-04-30',
                'actual_end_date' => '2024-04-25',
                'budget' => 500000.00,
                'actual_cost' => 480000.00,
                'progress_percentage' => 100.00,
                'location' => 'المنطقة الشمالية',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'دراسة جدوى شاملة لمشروع محطة طاقة شمسية بقدرة 100 ميجاوات',
                'notes' => 'تم تسليم الدراسة للعميل',
                'is_active' => false,
                'created_by' => 1,
            ],
            [
                'unit_id' => 5,
                'department_id' => 8,
                'code' => 'PRJ-008',
                'name' => 'خطة التحول الرقمي للبنك الوطني',
                'name_en' => 'National Bank Digital Transformation Plan',
                'type' => 'consulting',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-07-01',
                'planned_end_date' => '2025-12-31',
                'actual_end_date' => null,
                'budget' => 12000000.00,
                'actual_cost' => 5500000.00,
                'progress_percentage' => 45.00,
                'location' => 'الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'خطة استراتيجية شاملة للتحول الرقمي',
                'notes' => 'تم الانتهاء من المرحلة الأولى (التحليل)',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 5,
                'department_id' => 9,
                'code' => 'PRJ-009',
                'name' => 'دراسة جدوى مصنع الأدوية',
                'name_en' => 'Pharmaceutical Factory Feasibility Study',
                'type' => 'consulting',
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => '2024-10-01',
                'planned_end_date' => '2025-02-28',
                'actual_end_date' => null,
                'budget' => 800000.00,
                'actual_cost' => 350000.00,
                'progress_percentage' => 43.00,
                'location' => 'جدة',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'دراسة جدوى اقتصادية وفنية لمصنع أدوية',
                'notes' => 'في مرحلة جمع البيانات',
                'is_active' => true,
                'created_by' => 1,
            ],
            
            // مشاريع النور لإدارة الأصول
            [
                'unit_id' => 6,
                'department_id' => 10,
                'code' => 'PRJ-010',
                'name' => 'صندوق الاستثمار العقاري',
                'name_en' => 'Real Estate Investment Fund',
                'type' => 'investment',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2023-01-01',
                'planned_end_date' => '2028-12-31',
                'actual_end_date' => null,
                'budget' => 1000000000.00,
                'actual_cost' => 650000000.00,
                'progress_percentage' => 65.00,
                'location' => 'مناطق متعددة',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'صندوق استثماري عقاري بأصول متنوعة',
                'notes' => 'تم استثمار 65% من رأس المال',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 6,
                'department_id' => 11,
                'code' => 'PRJ-011',
                'name' => 'محفظة الأسهم المتوازنة',
                'name_en' => 'Balanced Stock Portfolio',
                'type' => 'investment',
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => '2024-01-01',
                'planned_end_date' => '2026-12-31',
                'actual_end_date' => null,
                'budget' => 500000000.00,
                'actual_cost' => 480000000.00,
                'progress_percentage' => 96.00,
                'location' => 'السوق المالية السعودية',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'محفظة استثمارية متوازنة في الأسهم المحلية',
                'notes' => 'أداء المحفظة يفوق المؤشر بنسبة 3.5%',
                'is_active' => true,
                'created_by' => 1,
            ],
            
            // مشاريع مصنع الفجر للبلاستيك
            [
                'unit_id' => 8,
                'department_id' => 12,
                'code' => 'PRJ-012',
                'name' => 'خط إنتاج الأنابيب الجديد',
                'name_en' => 'New Pipes Production Line',
                'type' => 'manufacturing',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-03-01',
                'planned_end_date' => '2025-09-30',
                'actual_end_date' => null,
                'budget' => 45000000.00,
                'actual_cost' => 28000000.00,
                'progress_percentage' => 62.00,
                'location' => 'مصنع الدمام',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'خط إنتاج حديث لأنابيب البولي إيثيلين',
                'notes' => 'تم تركيب 70% من المعدات',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 8,
                'department_id' => 13,
                'code' => 'PRJ-013',
                'name' => 'نظام إدارة الجودة ISO 9001',
                'name_en' => 'ISO 9001 Quality Management System',
                'type' => 'quality',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-06-01',
                'planned_end_date' => '2025-06-30',
                'actual_end_date' => null,
                'budget' => 2500000.00,
                'actual_cost' => 1400000.00,
                'progress_percentage' => 56.00,
                'location' => 'جميع المصانع',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'تطبيق نظام إدارة الجودة والحصول على شهادة ISO 9001',
                'notes' => 'تم الانتهاء من التوثيق',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 8,
                'department_id' => 14,
                'code' => 'PRJ-014',
                'name' => 'تطوير نظام الصيانة الوقائية',
                'name_en' => 'Preventive Maintenance System Development',
                'type' => 'maintenance',
                'status' => 'completed',
                'priority' => 'medium',
                'start_date' => '2023-09-01',
                'planned_end_date' => '2024-03-31',
                'actual_end_date' => '2024-03-20',
                'budget' => 3000000.00,
                'actual_cost' => 2850000.00,
                'progress_percentage' => 100.00,
                'location' => 'مصنع الدمام',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'نظام صيانة وقائية شامل لجميع المعدات',
                'notes' => 'تم تطبيق النظام بنجاح',
                'is_active' => false,
                'created_by' => 1,
            ],
            
            // مشاريع مصنع الفجر للكيماويات
            [
                'unit_id' => 9,
                'department_id' => 15,
                'code' => 'PRJ-015',
                'name' => 'مشروع إنتاج البوليمرات',
                'name_en' => 'Polymers Production Project',
                'type' => 'manufacturing',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2023-01-01',
                'planned_end_date' => '2025-12-31',
                'actual_end_date' => null,
                'budget' => 250000000.00,
                'actual_cost' => 175000000.00,
                'progress_percentage' => 70.00,
                'location' => 'مصنع الجبيل',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مشروع إنتاج البوليمرات الصناعية',
                'notes' => 'المشروع في المرحلة النهائية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 9,
                'department_id' => 16,
                'code' => 'PRJ-016',
                'name' => 'نظام السلامة البيئية',
                'name_en' => 'Environmental Safety System',
                'type' => 'safety',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-04-01',
                'planned_end_date' => '2025-04-30',
                'actual_end_date' => null,
                'budget' => 15000000.00,
                'actual_cost' => 8000000.00,
                'progress_percentage' => 53.00,
                'location' => 'مصنع الجبيل',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'نظام شامل للسلامة البيئية ومعالجة النفايات',
                'notes' => 'تم تركيب محطة معالجة النفايات',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 9,
                'department_id' => 17,
                'code' => 'PRJ-017',
                'name' => 'مختبر التحاليل المتقدم',
                'name_en' => 'Advanced Analysis Laboratory',
                'type' => 'research',
                'status' => 'completed',
                'priority' => 'medium',
                'start_date' => '2023-06-01',
                'planned_end_date' => '2024-06-30',
                'actual_end_date' => '2024-05-15',
                'budget' => 18000000.00,
                'actual_cost' => 17500000.00,
                'progress_percentage' => 100.00,
                'location' => 'مصنع الجبيل',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مختبر مجهز بأحدث أجهزة التحليل الكيماوي',
                'notes' => 'المختبر قيد التشغيل',
                'is_active' => false,
                'created_by' => 1,
            ],
            
            // مشاريع مركز الأبحاث
            [
                'unit_id' => 12,
                'department_id' => 18,
                'code' => 'PRJ-018',
                'name' => 'تطوير بوليمر صديق للبيئة',
                'name_en' => 'Eco-Friendly Polymer Development',
                'type' => 'research',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-01-01',
                'planned_end_date' => '2026-12-31',
                'actual_end_date' => null,
                'budget' => 35000000.00,
                'actual_cost' => 12000000.00,
                'progress_percentage' => 34.00,
                'location' => 'مركز الأبحاث - الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'بحث وتطوير بوليمر قابل للتحلل الحيوي',
                'notes' => 'تم تطوير 3 نماذج أولية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 12,
                'department_id' => 18,
                'code' => 'PRJ-019',
                'name' => 'نظام تدوير النفايات البلاستيكية',
                'name_en' => 'Plastic Waste Recycling System',
                'type' => 'research',
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => '2024-05-01',
                'planned_end_date' => '2025-11-30',
                'actual_end_date' => null,
                'budget' => 20000000.00,
                'actual_cost' => 9000000.00,
                'progress_percentage' => 45.00,
                'location' => 'مركز الأبحاث - الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'تطوير تقنية متقدمة لتدوير النفايات البلاستيكية',
                'notes' => 'تم بناء نموذج تجريبي',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 12,
                'department_id' => 18,
                'code' => 'PRJ-020',
                'name' => 'دراسة تأثير البلاستيك على البيئة',
                'name_en' => 'Plastic Environmental Impact Study',
                'type' => 'research',
                'status' => 'completed',
                'priority' => 'low',
                'start_date' => '2023-03-01',
                'planned_end_date' => '2024-03-31',
                'actual_end_date' => '2024-02-28',
                'budget' => 5000000.00,
                'actual_cost' => 4800000.00,
                'progress_percentage' => 100.00,
                'location' => 'مركز الأبحاث - الرياض',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'دراسة شاملة لتأثير المواد البلاستيكية على البيئة',
                'notes' => 'تم نشر الدراسة في مجلة علمية',
                'is_active' => false,
                'created_by' => 1,
            ],
            
            // مشاريع إضافية متنوعة
            [
                'unit_id' => 1,
                'department_id' => 2,
                'code' => 'PRJ-021',
                'name' => 'حملة تسويقية للمشاريع الجديدة',
                'name_en' => 'New Projects Marketing Campaign',
                'type' => 'marketing',
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => '2024-11-01',
                'planned_end_date' => '2025-04-30',
                'actual_end_date' => null,
                'budget' => 12000000.00,
                'actual_cost' => 3000000.00,
                'progress_percentage' => 25.00,
                'location' => 'جميع المناطق',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'حملة تسويقية شاملة للمشاريع العقارية الجديدة',
                'notes' => 'تم إطلاق الحملة الرقمية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 2,
                'department_id' => 4,
                'code' => 'PRJ-022',
                'name' => 'تطوير نظام الشراء الإلكتروني',
                'name_en' => 'E-Procurement System Development',
                'type' => 'technology',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-08-01',
                'planned_end_date' => '2025-02-28',
                'actual_end_date' => null,
                'budget' => 6000000.00,
                'actual_cost' => 3500000.00,
                'progress_percentage' => 58.00,
                'location' => 'المقر الرئيسي',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'نظام شراء إلكتروني متكامل',
                'notes' => 'تم الانتهاء من مرحلة التطوير',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 5,
                'department_id' => 7,
                'code' => 'PRJ-023',
                'name' => 'استشارات إعادة الهيكلة المالية',
                'name_en' => 'Financial Restructuring Consulting',
                'type' => 'consulting',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-09-01',
                'planned_end_date' => '2025-03-31',
                'actual_end_date' => null,
                'budget' => 8000000.00,
                'actual_cost' => 4800000.00,
                'progress_percentage' => 60.00,
                'location' => 'جدة',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مشروع استشاري لإعادة هيكلة شركة صناعية',
                'notes' => 'تم الانتهاء من التحليل المالي',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 8,
                'department_id' => 12,
                'code' => 'PRJ-024',
                'name' => 'توسعة المصنع - المرحلة الثانية',
                'name_en' => 'Factory Expansion - Phase 2',
                'type' => 'construction',
                'status' => 'planning',
                'priority' => 'medium',
                'start_date' => '2025-06-01',
                'planned_end_date' => '2027-06-30',
                'actual_end_date' => null,
                'budget' => 120000000.00,
                'actual_cost' => 2000000.00,
                'progress_percentage' => 2.00,
                'location' => 'مصنع الدمام',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'توسعة المصنع لمضاعفة الطاقة الإنتاجية',
                'notes' => 'في مرحلة التصاميم الأولية',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'unit_id' => 9,
                'department_id' => 15,
                'code' => 'PRJ-025',
                'name' => 'مشروع الطاقة البديلة',
                'name_en' => 'Alternative Energy Project',
                'type' => 'energy',
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => '2024-02-01',
                'planned_end_date' => '2026-02-28',
                'actual_end_date' => null,
                'budget' => 80000000.00,
                'actual_cost' => 35000000.00,
                'progress_percentage' => 43.00,
                'location' => 'مصنع الجبيل',
                'client_id' => null,
                'manager_id' => null,
                'description' => 'مشروع لتوليد الطاقة من الطاقة الشمسية',
                'notes' => 'تم تركيب 50% من الألواح الشمسية',
                'is_active' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }

        $this->command->info('✅ تم إنشاء 25 مشروع بنجاح');
    }
}
