<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Unit;
use App\Models\Holding;
use Illuminate\Support\Facades\DB;

/**
 * UnitSeeder - بيانات تجريبية للوحدات التنظيمية
 * 
 * ينشئ 12 وحدة (شركات، فروع، أقسام) تابعة للشركات القابضة
 */
class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('units')->delete();
        
        $holdings = Holding::all();
        
        if ($holdings->count() < 3) {
            $this->command->error('⚠️ يجب تشغيل HoldingSeeder أولاً');
            return;
        }

        $units = [
            // وحدات مجموعة العباسي
            [
                'holding_id' => $holdings[0]->id,
                'parent_id' => null,
                'code' => 'UNIT-001',
                'name' => 'شركة العباسي العقارية',
                'name_en' => 'Al-Abbasi Real Estate Company',
                'type' => 'company',
                'email' => 'realestate@alabasi.com',
                'phone' => '+966112345680',
                'fax' => '+966112345681',
                'address' => 'برج العباسي، طريق الملك فهد',
                'city' => 'الرياض',
                'country' => 'السعودية',
                'postal_code' => '11564',
                'tax_number' => '300123456789004',
                'commercial_register' => '1010123457',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2010-06-01',
                'end_date' => null,
                'notes' => 'شركة متخصصة في التطوير العقاري والاستثمار',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[0]->id,
                'parent_id' => null,
                'code' => 'UNIT-002',
                'name' => 'شركة العباسي للتجارة',
                'name_en' => 'Al-Abbasi Trading Company',
                'type' => 'company',
                'email' => 'trading@alabasi.com',
                'phone' => '+966112345682',
                'fax' => '+966112345683',
                'address' => 'حي الملز، الرياض',
                'city' => 'الرياض',
                'country' => 'السعودية',
                'postal_code' => '11564',
                'tax_number' => '300123456789005',
                'commercial_register' => '1010123458',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2011-03-15',
                'end_date' => null,
                'notes' => 'شركة تجارية متنوعة الأنشطة',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[0]->id,
                'parent_id' => 1, // تابع للعقارية
                'code' => 'UNIT-003',
                'name' => 'فرع العباسي العقارية - جدة',
                'name_en' => 'Al-Abbasi Real Estate - Jeddah Branch',
                'type' => 'branch',
                'email' => 'jeddah@alabasi-re.com',
                'phone' => '+966126543220',
                'fax' => '+966126543221',
                'address' => 'طريق الكورنيش، حي الشاطئ',
                'city' => 'جدة',
                'country' => 'السعودية',
                'postal_code' => '23441',
                'tax_number' => null,
                'commercial_register' => null,
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2012-09-01',
                'end_date' => null,
                'notes' => 'فرع متخصص في المشاريع العقارية بالمنطقة الغربية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[0]->id,
                'parent_id' => 1, // تابع للعقارية
                'code' => 'UNIT-004',
                'name' => 'فرع العباسي العقارية - الدمام',
                'name_en' => 'Al-Abbasi Real Estate - Dammam Branch',
                'type' => 'branch',
                'email' => 'dammam@alabasi-re.com',
                'phone' => '+966133456791',
                'fax' => '+966133456792',
                'address' => 'طريق الملك عبدالعزيز',
                'city' => 'الدمام',
                'country' => 'السعودية',
                'postal_code' => '31421',
                'tax_number' => null,
                'commercial_register' => null,
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2013-01-15',
                'end_date' => null,
                'notes' => 'فرع متخصص في المشاريع العقارية بالمنطقة الشرقية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            
            // وحدات مجموعة النور
            [
                'holding_id' => $holdings[1]->id,
                'parent_id' => null,
                'code' => 'UNIT-005',
                'name' => 'شركة النور للاستشارات المالية',
                'name_en' => 'Al-Noor Financial Consulting',
                'type' => 'company',
                'email' => 'consulting@alnoor.com',
                'phone' => '+966126543230',
                'fax' => '+966126543231',
                'address' => 'برج النور، شارع التحلية',
                'city' => 'جدة',
                'country' => 'السعودية',
                'postal_code' => '23441',
                'tax_number' => '300234567890004',
                'commercial_register' => '4030234568',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2015-09-01',
                'end_date' => null,
                'notes' => 'شركة استشارات مالية واستثمارية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[1]->id,
                'parent_id' => null,
                'code' => 'UNIT-006',
                'name' => 'شركة النور لإدارة الأصول',
                'name_en' => 'Al-Noor Asset Management',
                'type' => 'company',
                'email' => 'assets@alnoor.com',
                'phone' => '+966126543240',
                'fax' => '+966126543241',
                'address' => 'حي الزهراء، جدة',
                'city' => 'جدة',
                'country' => 'السعودية',
                'postal_code' => '23441',
                'tax_number' => '300234567890005',
                'commercial_register' => '4030234569',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2016-02-01',
                'end_date' => null,
                'notes' => 'شركة متخصصة في إدارة الأصول والمحافظ الاستثمارية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[1]->id,
                'parent_id' => 5, // تابع للاستشارات
                'code' => 'UNIT-007',
                'name' => 'قسم الاستشارات الضريبية',
                'name_en' => 'Tax Consulting Division',
                'type' => 'division',
                'email' => 'tax@alnoor-consulting.com',
                'phone' => '+966126543232',
                'fax' => null,
                'address' => 'برج النور، الطابق الخامس',
                'city' => 'جدة',
                'country' => 'السعودية',
                'postal_code' => '23441',
                'tax_number' => null,
                'commercial_register' => null,
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2017-01-01',
                'end_date' => null,
                'notes' => 'قسم متخصص في الاستشارات الضريبية والزكوية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            
            // وحدات مجموعة الفجر
            [
                'holding_id' => $holdings[2]->id,
                'parent_id' => null,
                'code' => 'UNIT-008',
                'name' => 'مصنع الفجر للبلاستيك',
                'name_en' => 'Al-Fajr Plastic Factory',
                'type' => 'company',
                'email' => 'plastic@alfajr.com',
                'phone' => '+966133456800',
                'fax' => '+966133456801',
                'address' => 'المدينة الصناعية الثانية',
                'city' => 'الدمام',
                'country' => 'السعودية',
                'postal_code' => '31421',
                'tax_number' => '300345678901004',
                'commercial_register' => '2050345679',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2008-06-01',
                'end_date' => null,
                'notes' => 'مصنع متخصص في إنتاج المواد البلاستيكية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[2]->id,
                'parent_id' => null,
                'code' => 'UNIT-009',
                'name' => 'مصنع الفجر للكيماويات',
                'name_en' => 'Al-Fajr Chemical Factory',
                'type' => 'company',
                'email' => 'chemical@alfajr.com',
                'phone' => '+966133456810',
                'fax' => '+966133456811',
                'address' => 'المدينة الصناعية الثالثة',
                'city' => 'الجبيل',
                'country' => 'السعودية',
                'postal_code' => '31951',
                'tax_number' => '300345678901005',
                'commercial_register' => '2050345680',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2010-03-01',
                'end_date' => null,
                'notes' => 'مصنع متخصص في إنتاج المواد الكيماوية الصناعية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[2]->id,
                'parent_id' => 8, // تابع لمصنع البلاستيك
                'code' => 'UNIT-010',
                'name' => 'خط إنتاج الأنابيب',
                'name_en' => 'Pipes Production Line',
                'type' => 'division',
                'email' => 'pipes@alfajr-plastic.com',
                'phone' => '+966133456802',
                'fax' => null,
                'address' => 'المدينة الصناعية الثانية - القسم أ',
                'city' => 'الدمام',
                'country' => 'السعودية',
                'postal_code' => '31421',
                'tax_number' => null,
                'commercial_register' => null,
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2009-01-15',
                'end_date' => null,
                'notes' => 'خط إنتاج متخصص في تصنيع الأنابيب البلاستيكية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[2]->id,
                'parent_id' => 8, // تابع لمصنع البلاستيك
                'code' => 'UNIT-011',
                'name' => 'خط إنتاج العبوات',
                'name_en' => 'Containers Production Line',
                'type' => 'division',
                'email' => 'containers@alfajr-plastic.com',
                'phone' => '+966133456803',
                'fax' => null,
                'address' => 'المدينة الصناعية الثانية - القسم ب',
                'city' => 'الدمام',
                'country' => 'السعودية',
                'postal_code' => '31421',
                'tax_number' => null,
                'commercial_register' => null,
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2011-06-01',
                'end_date' => null,
                'notes' => 'خط إنتاج متخصص في تصنيع العبوات البلاستيكية',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'holding_id' => $holdings[2]->id,
                'parent_id' => null,
                'code' => 'UNIT-012',
                'name' => 'مركز الأبحاث والتطوير',
                'name_en' => 'Research & Development Center',
                'type' => 'subsidiary',
                'email' => 'rd@alfajr.com',
                'phone' => '+966133456820',
                'fax' => '+966133456821',
                'address' => 'مدينة الملك عبدالعزيز للعلوم والتقنية',
                'city' => 'الرياض',
                'country' => 'السعودية',
                'postal_code' => '11442',
                'tax_number' => '300345678901006',
                'commercial_register' => '1010345681',
                'manager_id' => null,
                'is_active' => true,
                'start_date' => '2018-01-01',
                'end_date' => null,
                'notes' => 'مركز متخصص في الأبحاث والتطوير الصناعي',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($units as $unit) {
            Unit::create($unit);
        }

        $this->command->info('✅ تم إنشاء 12 وحدة تنظيمية بنجاح');
    }
}
