<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AccountBalance;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * AccountBalanceApiController
 * 
 * RESTful API Controller for AccountBalance
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class AccountBalanceApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/account-balances",
     *     summary="Get all AccountBalance records",
     *     tags={"AccountBalance"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $accountBalances = AccountBalance::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $accountBalances->items(),
                'meta' => [
                    'current_page' => $accountBalances->currentPage(),
                    'per_page' => $accountBalances->perPage(),
                    'total' => $accountBalances->total(),
                    'last_page' => $accountBalances->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/account-balances",
     *     summary="Create a new AccountBalance",
     *     tags={"AccountBalance"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $accountBalance = AccountBalance::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'AccountBalance created successfully',
                'data' => $accountBalance
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create AccountBalance',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/account-balances/{id}",
     *     summary="Get a specific AccountBalance",
     *     tags={"AccountBalance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $accountBalance = AccountBalance::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $accountBalance
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'AccountBalance not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/account-balances/{id}",
     *     summary="Update a AccountBalance",
     *     tags={"AccountBalance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $accountBalance = AccountBalance::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $accountBalance->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'AccountBalance updated successfully',
                'data' => $accountBalance
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update AccountBalance',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/account-balances/{id}",
     *     summary="Delete a AccountBalance",
     *     tags={"AccountBalance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $accountBalance = AccountBalance::findOrFail($id);
            $accountBalance->delete();

            return response()->json([
                'success' => true,
                'message' => 'AccountBalance deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete AccountBalance',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
