<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AccountType;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * AccountTypeApiController
 * 
 * RESTful API Controller for AccountType
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class AccountTypeApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/account-types",
     *     summary="Get all AccountType records",
     *     tags={"AccountType"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $accountTypes = AccountType::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $accountTypes->items(),
                'meta' => [
                    'current_page' => $accountTypes->currentPage(),
                    'per_page' => $accountTypes->perPage(),
                    'total' => $accountTypes->total(),
                    'last_page' => $accountTypes->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/account-types",
     *     summary="Create a new AccountType",
     *     tags={"AccountType"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $accountType = AccountType::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'AccountType created successfully',
                'data' => $accountType
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create AccountType',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/account-types/{id}",
     *     summary="Get a specific AccountType",
     *     tags={"AccountType"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $accountType = AccountType::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $accountType
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'AccountType not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/account-types/{id}",
     *     summary="Update a AccountType",
     *     tags={"AccountType"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $accountType = AccountType::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $accountType->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'AccountType updated successfully',
                'data' => $accountType
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update AccountType',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/account-types/{id}",
     *     summary="Delete a AccountType",
     *     tags={"AccountType"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $accountType = AccountType::findOrFail($id);
            $accountType->delete();

            return response()->json([
                'success' => true,
                'message' => 'AccountType deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete AccountType',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
