<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AIConversation;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * AIConversationApiController
 * 
 * RESTful API Controller for AIConversation
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class AIConversationApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/ai-conversations",
     *     summary="Get all AIConversation records",
     *     tags={"AIConversation"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $aIConversations = AIConversation::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $aIConversations->items(),
                'meta' => [
                    'current_page' => $aIConversations->currentPage(),
                    'per_page' => $aIConversations->perPage(),
                    'total' => $aIConversations->total(),
                    'last_page' => $aIConversations->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/ai-conversations",
     *     summary="Create a new AIConversation",
     *     tags={"AIConversation"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $aIConversation = AIConversation::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'AIConversation created successfully',
                'data' => $aIConversation
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create AIConversation',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/ai-conversations/{id}",
     *     summary="Get a specific AIConversation",
     *     tags={"AIConversation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $aIConversation = AIConversation::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $aIConversation
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'AIConversation not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/ai-conversations/{id}",
     *     summary="Update a AIConversation",
     *     tags={"AIConversation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $aIConversation = AIConversation::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $aIConversation->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'AIConversation updated successfully',
                'data' => $aIConversation
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update AIConversation',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/ai-conversations/{id}",
     *     summary="Delete a AIConversation",
     *     tags={"AIConversation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $aIConversation = AIConversation::findOrFail($id);
            $aIConversation->delete();

            return response()->json([
                'success' => true,
                'message' => 'AIConversation deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete AIConversation',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
