<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AiSetting;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * AiSettingApiController
 * 
 * RESTful API Controller for AiSetting
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class AiSettingApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/ai-settings",
     *     summary="Get all AiSetting records",
     *     tags={"AiSetting"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $aiSettings = AiSetting::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $aiSettings->items(),
                'meta' => [
                    'current_page' => $aiSettings->currentPage(),
                    'per_page' => $aiSettings->perPage(),
                    'total' => $aiSettings->total(),
                    'last_page' => $aiSettings->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/ai-settings",
     *     summary="Create a new AiSetting",
     *     tags={"AiSetting"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $aiSetting = AiSetting::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'AiSetting created successfully',
                'data' => $aiSetting
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create AiSetting',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/ai-settings/{id}",
     *     summary="Get a specific AiSetting",
     *     tags={"AiSetting"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $aiSetting = AiSetting::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $aiSetting
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'AiSetting not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/ai-settings/{id}",
     *     summary="Update a AiSetting",
     *     tags={"AiSetting"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $aiSetting = AiSetting::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $aiSetting->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'AiSetting updated successfully',
                'data' => $aiSetting
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update AiSetting',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/ai-settings/{id}",
     *     summary="Delete a AiSetting",
     *     tags={"AiSetting"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $aiSetting = AiSetting::findOrFail($id);
            $aiSetting->delete();

            return response()->json([
                'success' => true,
                'message' => 'AiSetting deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete AiSetting',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
