<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ApiLog;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ApiLogApiController
 * 
 * RESTful API Controller for ApiLog
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ApiLogApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/api-logs",
     *     summary="Get all ApiLog records",
     *     tags={"ApiLog"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $apiLogs = ApiLog::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $apiLogs->items(),
                'meta' => [
                    'current_page' => $apiLogs->currentPage(),
                    'per_page' => $apiLogs->perPage(),
                    'total' => $apiLogs->total(),
                    'last_page' => $apiLogs->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/api-logs",
     *     summary="Create a new ApiLog",
     *     tags={"ApiLog"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $apiLog = ApiLog::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ApiLog created successfully',
                'data' => $apiLog
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ApiLog',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/api-logs/{id}",
     *     summary="Get a specific ApiLog",
     *     tags={"ApiLog"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $apiLog = ApiLog::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $apiLog
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ApiLog not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/api-logs/{id}",
     *     summary="Update a ApiLog",
     *     tags={"ApiLog"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $apiLog = ApiLog::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $apiLog->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ApiLog updated successfully',
                'data' => $apiLog
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ApiLog',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/api-logs/{id}",
     *     summary="Delete a ApiLog",
     *     tags={"ApiLog"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $apiLog = ApiLog::findOrFail($id);
            $apiLog->delete();

            return response()->json([
                'success' => true,
                'message' => 'ApiLog deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ApiLog',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
