<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Cashiers\Cashier;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CashierApiController
 * 
 * RESTful API Controller for Cashier
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CashierApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/cashiers",
     *     summary="Get all Cashier records",
     *     tags={"Cashier"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $cashiers = Cashier::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $cashiers->items(),
                'meta' => [
                    'current_page' => $cashiers->currentPage(),
                    'per_page' => $cashiers->perPage(),
                    'total' => $cashiers->total(),
                    'last_page' => $cashiers->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/cashiers",
     *     summary="Create a new Cashier",
     *     tags={"Cashier"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $cashier = Cashier::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'Cashier created successfully',
                'data' => $cashier
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create Cashier',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/cashiers/{id}",
     *     summary="Get a specific Cashier",
     *     tags={"Cashier"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $cashier = Cashier::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $cashier
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Cashier not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/cashiers/{id}",
     *     summary="Update a Cashier",
     *     tags={"Cashier"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $cashier = Cashier::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $cashier->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'Cashier updated successfully',
                'data' => $cashier
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update Cashier',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/cashiers/{id}",
     *     summary="Delete a Cashier",
     *     tags={"Cashier"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $cashier = Cashier::findOrFail($id);
            $cashier->delete();

            return response()->json([
                'success' => true,
                'message' => 'Cashier deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete Cashier',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
