<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CashBox;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CashBoxApiController
 * 
 * RESTful API Controller for CashBox
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CashBoxApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/cash-boxs",
     *     summary="Get all CashBox records",
     *     tags={"CashBox"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $cashBoxs = CashBox::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $cashBoxs->items(),
                'meta' => [
                    'current_page' => $cashBoxs->currentPage(),
                    'per_page' => $cashBoxs->perPage(),
                    'total' => $cashBoxs->total(),
                    'last_page' => $cashBoxs->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/cash-boxs",
     *     summary="Create a new CashBox",
     *     tags={"CashBox"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $cashBox = CashBox::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'CashBox created successfully',
                'data' => $cashBox
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CashBox',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/cash-boxs/{id}",
     *     summary="Get a specific CashBox",
     *     tags={"CashBox"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $cashBox = CashBox::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $cashBox
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'CashBox not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/cash-boxs/{id}",
     *     summary="Update a CashBox",
     *     tags={"CashBox"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $cashBox = CashBox::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $cashBox->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'CashBox updated successfully',
                'data' => $cashBox
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update CashBox',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/cash-boxs/{id}",
     *     summary="Delete a CashBox",
     *     tags={"CashBox"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $cashBox = CashBox::findOrFail($id);
            $cashBox->delete();

            return response()->json([
                'success' => true,
                'message' => 'CashBox deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete CashBox',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
