<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ChartAccount;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ChartAccountApiController
 * 
 * RESTful API Controller for ChartAccount
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ChartAccountApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/chart-accounts",
     *     summary="Get all ChartAccount records",
     *     tags={"ChartAccount"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $chartAccounts = ChartAccount::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $chartAccounts->items(),
                'meta' => [
                    'current_page' => $chartAccounts->currentPage(),
                    'per_page' => $chartAccounts->perPage(),
                    'total' => $chartAccounts->total(),
                    'last_page' => $chartAccounts->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/chart-accounts",
     *     summary="Create a new ChartAccount",
     *     tags={"ChartAccount"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $chartAccount = ChartAccount::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ChartAccount created successfully',
                'data' => $chartAccount
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ChartAccount',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/chart-accounts/{id}",
     *     summary="Get a specific ChartAccount",
     *     tags={"ChartAccount"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $chartAccount = ChartAccount::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $chartAccount
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ChartAccount not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/chart-accounts/{id}",
     *     summary="Update a ChartAccount",
     *     tags={"ChartAccount"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $chartAccount = ChartAccount::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $chartAccount->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ChartAccount updated successfully',
                'data' => $chartAccount
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ChartAccount',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/chart-accounts/{id}",
     *     summary="Delete a ChartAccount",
     *     tags={"ChartAccount"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $chartAccount = ChartAccount::findOrFail($id);
            $chartAccount->delete();

            return response()->json([
                'success' => true,
                'message' => 'ChartAccount deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ChartAccount',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
