<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ClientGene;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ClientGeneApiController
 * 
 * RESTful API Controller for ClientGene
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ClientGeneApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/client-genes",
     *     summary="Get all ClientGene records",
     *     tags={"ClientGene"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $clientGenes = ClientGene::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $clientGenes->items(),
                'meta' => [
                    'current_page' => $clientGenes->currentPage(),
                    'per_page' => $clientGenes->perPage(),
                    'total' => $clientGenes->total(),
                    'last_page' => $clientGenes->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/client-genes",
     *     summary="Create a new ClientGene",
     *     tags={"ClientGene"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $clientGene = ClientGene::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ClientGene created successfully',
                'data' => $clientGene
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ClientGene',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/client-genes/{id}",
     *     summary="Get a specific ClientGene",
     *     tags={"ClientGene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $clientGene = ClientGene::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $clientGene
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ClientGene not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/client-genes/{id}",
     *     summary="Update a ClientGene",
     *     tags={"ClientGene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $clientGene = ClientGene::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $clientGene->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ClientGene updated successfully',
                'data' => $clientGene
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ClientGene',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/client-genes/{id}",
     *     summary="Delete a ClientGene",
     *     tags={"ClientGene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $clientGene = ClientGene::findOrFail($id);
            $clientGene->delete();

            return response()->json([
                'success' => true,
                'message' => 'ClientGene deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ClientGene',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
