<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CostCenter;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CostCenterApiController
 * 
 * RESTful API Controller for CostCenter
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CostCenterApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/cost-centers",
     *     summary="Get all CostCenter records",
     *     tags={"CostCenter"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $costCenters = CostCenter::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $costCenters->items(),
                'meta' => [
                    'current_page' => $costCenters->currentPage(),
                    'per_page' => $costCenters->perPage(),
                    'total' => $costCenters->total(),
                    'last_page' => $costCenters->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/cost-centers",
     *     summary="Create a new CostCenter",
     *     tags={"CostCenter"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $costCenter = CostCenter::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'CostCenter created successfully',
                'data' => $costCenter
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CostCenter',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/cost-centers/{id}",
     *     summary="Get a specific CostCenter",
     *     tags={"CostCenter"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $costCenter = CostCenter::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $costCenter
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'CostCenter not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/cost-centers/{id}",
     *     summary="Update a CostCenter",
     *     tags={"CostCenter"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $costCenter = CostCenter::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $costCenter->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'CostCenter updated successfully',
                'data' => $costCenter
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update CostCenter',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/cost-centers/{id}",
     *     summary="Delete a CostCenter",
     *     tags={"CostCenter"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $costCenter = CostCenter::findOrFail($id);
            $costCenter->delete();

            return response()->json([
                'success' => true,
                'message' => 'CostCenter deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete CostCenter',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
