<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CustomerContact;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CustomerContactApiController
 * 
 * RESTful API Controller for CustomerContact
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CustomerContactApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/customer-contacts",
     *     summary="Get all CustomerContact records",
     *     tags={"CustomerContact"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $customerContacts = CustomerContact::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $customerContacts->items(),
                'meta' => [
                    'current_page' => $customerContacts->currentPage(),
                    'per_page' => $customerContacts->perPage(),
                    'total' => $customerContacts->total(),
                    'last_page' => $customerContacts->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/customer-contacts",
     *     summary="Create a new CustomerContact",
     *     tags={"CustomerContact"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerContact = CustomerContact::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerContact created successfully',
                'data' => $customerContact
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CustomerContact',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/customer-contacts/{id}",
     *     summary="Get a specific CustomerContact",
     *     tags={"CustomerContact"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $customerContact = CustomerContact::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $customerContact
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'CustomerContact not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/customer-contacts/{id}",
     *     summary="Update a CustomerContact",
     *     tags={"CustomerContact"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $customerContact = CustomerContact::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerContact->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerContact updated successfully',
                'data' => $customerContact
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update CustomerContact',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/customer-contacts/{id}",
     *     summary="Delete a CustomerContact",
     *     tags={"CustomerContact"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $customerContact = CustomerContact::findOrFail($id);
            $customerContact->delete();

            return response()->json([
                'success' => true,
                'message' => 'CustomerContact deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete CustomerContact',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
