<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CustomerAddress;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CustomerAddressApiController
 * 
 * RESTful API Controller for CustomerAddress
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CustomerAddressApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/customer-addresses",
     *     summary="Get all CustomerAddress records",
     *     tags={"CustomerAddress"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $customerAddresses = CustomerAddress::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $customerAddresses->items(),
                'meta' => [
                    'current_page' => $customerAddresses->currentPage(),
                    'per_page' => $customerAddresses->perPage(),
                    'total' => $customerAddresses->total(),
                    'last_page' => $customerAddresses->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/customer-addresses",
     *     summary="Create a new CustomerAddress",
     *     tags={"CustomerAddress"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerAddress = CustomerAddress::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerAddress created successfully',
                'data' => $customerAddress
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CustomerAddress',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/customer-addresses/{id}",
     *     summary="Get a specific CustomerAddress",
     *     tags={"CustomerAddress"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $customerAddress = CustomerAddress::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $customerAddress
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'CustomerAddress not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/customer-addresses/{id}",
     *     summary="Update a CustomerAddress",
     *     tags={"CustomerAddress"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $customerAddress = CustomerAddress::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerAddress->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerAddress updated successfully',
                'data' => $customerAddress
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update CustomerAddress',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/customer-addresses/{id}",
     *     summary="Delete a CustomerAddress",
     *     tags={"CustomerAddress"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $customerAddress = CustomerAddress::findOrFail($id);
            $customerAddress->delete();

            return response()->json([
                'success' => true,
                'message' => 'CustomerAddress deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete CustomerAddress',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
