<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CustomerCategory;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * CustomerCategoryApiController
 * 
 * RESTful API Controller for CustomerCategory
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class CustomerCategoryApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/customer-categories",
     *     summary="Get all CustomerCategory records",
     *     tags={"CustomerCategory"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $customerCategories = CustomerCategory::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $customerCategories->items(),
                'meta' => [
                    'current_page' => $customerCategories->currentPage(),
                    'per_page' => $customerCategories->perPage(),
                    'total' => $customerCategories->total(),
                    'last_page' => $customerCategories->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/customer-categories",
     *     summary="Create a new CustomerCategory",
     *     tags={"CustomerCategory"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerCategory = CustomerCategory::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerCategory created successfully',
                'data' => $customerCategory
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create CustomerCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/customer-categories/{id}",
     *     summary="Get a specific CustomerCategory",
     *     tags={"CustomerCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $customerCategory = CustomerCategory::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $customerCategory
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'CustomerCategory not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/customer-categories/{id}",
     *     summary="Update a CustomerCategory",
     *     tags={"CustomerCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $customerCategory = CustomerCategory::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $customerCategory->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'CustomerCategory updated successfully',
                'data' => $customerCategory
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update CustomerCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/customer-categories/{id}",
     *     summary="Delete a CustomerCategory",
     *     tags={"CustomerCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $customerCategory = CustomerCategory::findOrFail($id);
            $customerCategory->delete();

            return response()->json([
                'success' => true,
                'message' => 'CustomerCategory deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete CustomerCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
