<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Dashboard;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * DashboardApiController
 * 
 * RESTful API Controller for Dashboard
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class DashboardApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/dashboards",
     *     summary="Get all Dashboard records",
     *     tags={"Dashboard"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $dashboards = Dashboard::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $dashboards->items(),
                'meta' => [
                    'current_page' => $dashboards->currentPage(),
                    'per_page' => $dashboards->perPage(),
                    'total' => $dashboards->total(),
                    'last_page' => $dashboards->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/dashboards",
     *     summary="Create a new Dashboard",
     *     tags={"Dashboard"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $dashboard = Dashboard::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'Dashboard created successfully',
                'data' => $dashboard
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create Dashboard',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/dashboards/{id}",
     *     summary="Get a specific Dashboard",
     *     tags={"Dashboard"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $dashboard = Dashboard::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $dashboard
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Dashboard not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/dashboards/{id}",
     *     summary="Update a Dashboard",
     *     tags={"Dashboard"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $dashboard = Dashboard::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $dashboard->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'Dashboard updated successfully',
                'data' => $dashboard
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update Dashboard',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/dashboards/{id}",
     *     summary="Delete a Dashboard",
     *     tags={"Dashboard"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $dashboard = Dashboard::findOrFail($id);
            $dashboard->delete();

            return response()->json([
                'success' => true,
                'message' => 'Dashboard deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete Dashboard',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
