<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\DrugInteraction;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * DrugInteractionApiController
 * 
 * RESTful API Controller for DrugInteraction
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class DrugInteractionApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/drug-interactions",
     *     summary="Get all DrugInteraction records",
     *     tags={"DrugInteraction"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $drugInteractions = DrugInteraction::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $drugInteractions->items(),
                'meta' => [
                    'current_page' => $drugInteractions->currentPage(),
                    'per_page' => $drugInteractions->perPage(),
                    'total' => $drugInteractions->total(),
                    'last_page' => $drugInteractions->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/drug-interactions",
     *     summary="Create a new DrugInteraction",
     *     tags={"DrugInteraction"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $drugInteraction = DrugInteraction::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'DrugInteraction created successfully',
                'data' => $drugInteraction
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create DrugInteraction',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/drug-interactions/{id}",
     *     summary="Get a specific DrugInteraction",
     *     tags={"DrugInteraction"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $drugInteraction = DrugInteraction::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $drugInteraction
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'DrugInteraction not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/drug-interactions/{id}",
     *     summary="Update a DrugInteraction",
     *     tags={"DrugInteraction"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $drugInteraction = DrugInteraction::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $drugInteraction->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'DrugInteraction updated successfully',
                'data' => $drugInteraction
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update DrugInteraction',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/drug-interactions/{id}",
     *     summary="Delete a DrugInteraction",
     *     tags={"DrugInteraction"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $drugInteraction = DrugInteraction::findOrFail($id);
            $drugInteraction->delete();

            return response()->json([
                'success' => true,
                'message' => 'DrugInteraction deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete DrugInteraction',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
