<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\EmployeeDocument;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * EmployeeDocumentApiController
 * 
 * RESTful API Controller for EmployeeDocument
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class EmployeeDocumentApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/employee-documents",
     *     summary="Get all EmployeeDocument records",
     *     tags={"EmployeeDocument"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $employeeDocuments = EmployeeDocument::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $employeeDocuments->items(),
                'meta' => [
                    'current_page' => $employeeDocuments->currentPage(),
                    'per_page' => $employeeDocuments->perPage(),
                    'total' => $employeeDocuments->total(),
                    'last_page' => $employeeDocuments->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/employee-documents",
     *     summary="Create a new EmployeeDocument",
     *     tags={"EmployeeDocument"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $employeeDocument = EmployeeDocument::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'EmployeeDocument created successfully',
                'data' => $employeeDocument
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create EmployeeDocument',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/employee-documents/{id}",
     *     summary="Get a specific EmployeeDocument",
     *     tags={"EmployeeDocument"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $employeeDocument = EmployeeDocument::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $employeeDocument
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'EmployeeDocument not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/employee-documents/{id}",
     *     summary="Update a EmployeeDocument",
     *     tags={"EmployeeDocument"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $employeeDocument = EmployeeDocument::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $employeeDocument->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'EmployeeDocument updated successfully',
                'data' => $employeeDocument
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update EmployeeDocument',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/employee-documents/{id}",
     *     summary="Delete a EmployeeDocument",
     *     tags={"EmployeeDocument"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $employeeDocument = EmployeeDocument::findOrFail($id);
            $employeeDocument->delete();

            return response()->json([
                'success' => true,
                'message' => 'EmployeeDocument deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete EmployeeDocument',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
