<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\FiscalPeriod;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * FiscalPeriodApiController
 * 
 * RESTful API Controller for FiscalPeriod
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class FiscalPeriodApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/fiscal-periods",
     *     summary="Get all FiscalPeriod records",
     *     tags={"FiscalPeriod"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $fiscalPeriods = FiscalPeriod::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $fiscalPeriods->items(),
                'meta' => [
                    'current_page' => $fiscalPeriods->currentPage(),
                    'per_page' => $fiscalPeriods->perPage(),
                    'total' => $fiscalPeriods->total(),
                    'last_page' => $fiscalPeriods->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/fiscal-periods",
     *     summary="Create a new FiscalPeriod",
     *     tags={"FiscalPeriod"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $fiscalPeriod = FiscalPeriod::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'FiscalPeriod created successfully',
                'data' => $fiscalPeriod
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create FiscalPeriod',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/fiscal-periods/{id}",
     *     summary="Get a specific FiscalPeriod",
     *     tags={"FiscalPeriod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $fiscalPeriod = FiscalPeriod::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $fiscalPeriod
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'FiscalPeriod not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/fiscal-periods/{id}",
     *     summary="Update a FiscalPeriod",
     *     tags={"FiscalPeriod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $fiscalPeriod = FiscalPeriod::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $fiscalPeriod->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'FiscalPeriod updated successfully',
                'data' => $fiscalPeriod
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update FiscalPeriod',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/fiscal-periods/{id}",
     *     summary="Delete a FiscalPeriod",
     *     tags={"FiscalPeriod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $fiscalPeriod = FiscalPeriod::findOrFail($id);
            $fiscalPeriod->delete();

            return response()->json([
                'success' => true,
                'message' => 'FiscalPeriod deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete FiscalPeriod',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
