<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\FiscalYear;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * FiscalYearApiController
 * 
 * RESTful API Controller for FiscalYear
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class FiscalYearApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/fiscal-years",
     *     summary="Get all FiscalYear records",
     *     tags={"FiscalYear"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $fiscalYears = FiscalYear::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $fiscalYears->items(),
                'meta' => [
                    'current_page' => $fiscalYears->currentPage(),
                    'per_page' => $fiscalYears->perPage(),
                    'total' => $fiscalYears->total(),
                    'last_page' => $fiscalYears->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/fiscal-years",
     *     summary="Create a new FiscalYear",
     *     tags={"FiscalYear"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $fiscalYear = FiscalYear::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'FiscalYear created successfully',
                'data' => $fiscalYear
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create FiscalYear',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/fiscal-years/{id}",
     *     summary="Get a specific FiscalYear",
     *     tags={"FiscalYear"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $fiscalYear = FiscalYear::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $fiscalYear
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'FiscalYear not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/fiscal-years/{id}",
     *     summary="Update a FiscalYear",
     *     tags={"FiscalYear"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $fiscalYear = FiscalYear::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $fiscalYear->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'FiscalYear updated successfully',
                'data' => $fiscalYear
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update FiscalYear',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/fiscal-years/{id}",
     *     summary="Delete a FiscalYear",
     *     tags={"FiscalYear"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $fiscalYear = FiscalYear::findOrFail($id);
            $fiscalYear->delete();

            return response()->json([
                'success' => true,
                'message' => 'FiscalYear deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete FiscalYear',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
