<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Gene;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * GeneApiController
 * 
 * RESTful API Controller for Gene
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class GeneApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/genes",
     *     summary="Get all Gene records",
     *     tags={"Gene"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $genes = Gene::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $genes->items(),
                'meta' => [
                    'current_page' => $genes->currentPage(),
                    'per_page' => $genes->perPage(),
                    'total' => $genes->total(),
                    'last_page' => $genes->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/genes",
     *     summary="Create a new Gene",
     *     tags={"Gene"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $gene = Gene::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'Gene created successfully',
                'data' => $gene
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create Gene',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/genes/{id}",
     *     summary="Get a specific Gene",
     *     tags={"Gene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $gene = Gene::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $gene
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Gene not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/genes/{id}",
     *     summary="Update a Gene",
     *     tags={"Gene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $gene = Gene::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $gene->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'Gene updated successfully',
                'data' => $gene
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update Gene',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/genes/{id}",
     *     summary="Delete a Gene",
     *     tags={"Gene"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $gene = Gene::findOrFail($id);
            $gene->delete();

            return response()->json([
                'success' => true,
                'message' => 'Gene deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete Gene',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
