<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\GeneActivation;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * GeneActivationApiController
 * 
 * RESTful API Controller for GeneActivation
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class GeneActivationApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/gene-activations",
     *     summary="Get all GeneActivation records",
     *     tags={"GeneActivation"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $geneActivations = GeneActivation::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $geneActivations->items(),
                'meta' => [
                    'current_page' => $geneActivations->currentPage(),
                    'per_page' => $geneActivations->perPage(),
                    'total' => $geneActivations->total(),
                    'last_page' => $geneActivations->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/gene-activations",
     *     summary="Create a new GeneActivation",
     *     tags={"GeneActivation"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $geneActivation = GeneActivation::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'GeneActivation created successfully',
                'data' => $geneActivation
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create GeneActivation',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/gene-activations/{id}",
     *     summary="Get a specific GeneActivation",
     *     tags={"GeneActivation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $geneActivation = GeneActivation::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $geneActivation
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'GeneActivation not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/gene-activations/{id}",
     *     summary="Update a GeneActivation",
     *     tags={"GeneActivation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $geneActivation = GeneActivation::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $geneActivation->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'GeneActivation updated successfully',
                'data' => $geneActivation
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update GeneActivation',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/gene-activations/{id}",
     *     summary="Delete a GeneActivation",
     *     tags={"GeneActivation"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $geneActivation = GeneActivation::findOrFail($id);
            $geneActivation->delete();

            return response()->json([
                'success' => true,
                'message' => 'GeneActivation deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete GeneActivation',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
