<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\GeneFeature;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * GeneFeatureApiController
 * 
 * RESTful API Controller for GeneFeature
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class GeneFeatureApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/gene-features",
     *     summary="Get all GeneFeature records",
     *     tags={"GeneFeature"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $geneFeatures = GeneFeature::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $geneFeatures->items(),
                'meta' => [
                    'current_page' => $geneFeatures->currentPage(),
                    'per_page' => $geneFeatures->perPage(),
                    'total' => $geneFeatures->total(),
                    'last_page' => $geneFeatures->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/gene-features",
     *     summary="Create a new GeneFeature",
     *     tags={"GeneFeature"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $geneFeature = GeneFeature::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'GeneFeature created successfully',
                'data' => $geneFeature
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create GeneFeature',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/gene-features/{id}",
     *     summary="Get a specific GeneFeature",
     *     tags={"GeneFeature"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $geneFeature = GeneFeature::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $geneFeature
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'GeneFeature not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/gene-features/{id}",
     *     summary="Update a GeneFeature",
     *     tags={"GeneFeature"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $geneFeature = GeneFeature::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $geneFeature->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'GeneFeature updated successfully',
                'data' => $geneFeature
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update GeneFeature',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/gene-features/{id}",
     *     summary="Delete a GeneFeature",
     *     tags={"GeneFeature"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $geneFeature = GeneFeature::findOrFail($id);
            $geneFeature->delete();

            return response()->json([
                'success' => true,
                'message' => 'GeneFeature deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete GeneFeature',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
