<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\InsurancePolicy;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * InsurancePolicyApiController
 * 
 * RESTful API Controller for InsurancePolicy
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class InsurancePolicyApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/insurance-policies",
     *     summary="Get all InsurancePolicy records",
     *     tags={"InsurancePolicy"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $insurancePolicies = InsurancePolicy::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $insurancePolicies->items(),
                'meta' => [
                    'current_page' => $insurancePolicies->currentPage(),
                    'per_page' => $insurancePolicies->perPage(),
                    'total' => $insurancePolicies->total(),
                    'last_page' => $insurancePolicies->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/insurance-policies",
     *     summary="Create a new InsurancePolicy",
     *     tags={"InsurancePolicy"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $insurancePolicy = InsurancePolicy::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'InsurancePolicy created successfully',
                'data' => $insurancePolicy
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create InsurancePolicy',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/insurance-policies/{id}",
     *     summary="Get a specific InsurancePolicy",
     *     tags={"InsurancePolicy"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $insurancePolicy = InsurancePolicy::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $insurancePolicy
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'InsurancePolicy not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/insurance-policies/{id}",
     *     summary="Update a InsurancePolicy",
     *     tags={"InsurancePolicy"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $insurancePolicy = InsurancePolicy::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $insurancePolicy->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'InsurancePolicy updated successfully',
                'data' => $insurancePolicy
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update InsurancePolicy',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/insurance-policies/{id}",
     *     summary="Delete a InsurancePolicy",
     *     tags={"InsurancePolicy"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $insurancePolicy = InsurancePolicy::findOrFail($id);
            $insurancePolicy->delete();

            return response()->json([
                'success' => true,
                'message' => 'InsurancePolicy deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete InsurancePolicy',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
