<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ItemCategory;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ItemCategoryApiController
 * 
 * RESTful API Controller for ItemCategory
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ItemCategoryApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/item-categories",
     *     summary="Get all ItemCategory records",
     *     tags={"ItemCategory"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $itemCategories = ItemCategory::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $itemCategories->items(),
                'meta' => [
                    'current_page' => $itemCategories->currentPage(),
                    'per_page' => $itemCategories->perPage(),
                    'total' => $itemCategories->total(),
                    'last_page' => $itemCategories->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/item-categories",
     *     summary="Create a new ItemCategory",
     *     tags={"ItemCategory"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $itemCategory = ItemCategory::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ItemCategory created successfully',
                'data' => $itemCategory
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ItemCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/item-categories/{id}",
     *     summary="Get a specific ItemCategory",
     *     tags={"ItemCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $itemCategory = ItemCategory::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $itemCategory
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ItemCategory not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/item-categories/{id}",
     *     summary="Update a ItemCategory",
     *     tags={"ItemCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $itemCategory = ItemCategory::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $itemCategory->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ItemCategory updated successfully',
                'data' => $itemCategory
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ItemCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/item-categories/{id}",
     *     summary="Delete a ItemCategory",
     *     tags={"ItemCategory"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $itemCategory = ItemCategory::findOrFail($id);
            $itemCategory->delete();

            return response()->json([
                'success' => true,
                'message' => 'ItemCategory deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ItemCategory',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
