<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\JournalEntryLine;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * JournalEntryLineApiController
 * 
 * RESTful API Controller for JournalEntryLine
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class JournalEntryLineApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/journal-entry-lines",
     *     summary="Get all JournalEntryLine records",
     *     tags={"JournalEntryLine"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $journalEntryLines = JournalEntryLine::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $journalEntryLines->items(),
                'meta' => [
                    'current_page' => $journalEntryLines->currentPage(),
                    'per_page' => $journalEntryLines->perPage(),
                    'total' => $journalEntryLines->total(),
                    'last_page' => $journalEntryLines->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/journal-entry-lines",
     *     summary="Create a new JournalEntryLine",
     *     tags={"JournalEntryLine"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $journalEntryLine = JournalEntryLine::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'JournalEntryLine created successfully',
                'data' => $journalEntryLine
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create JournalEntryLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/journal-entry-lines/{id}",
     *     summary="Get a specific JournalEntryLine",
     *     tags={"JournalEntryLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $journalEntryLine = JournalEntryLine::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $journalEntryLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'JournalEntryLine not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/journal-entry-lines/{id}",
     *     summary="Update a JournalEntryLine",
     *     tags={"JournalEntryLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $journalEntryLine = JournalEntryLine::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $journalEntryLine->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'JournalEntryLine updated successfully',
                'data' => $journalEntryLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update JournalEntryLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/journal-entry-lines/{id}",
     *     summary="Delete a JournalEntryLine",
     *     tags={"JournalEntryLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $journalEntryLine = JournalEntryLine::findOrFail($id);
            $journalEntryLine->delete();

            return response()->json([
                'success' => true,
                'message' => 'JournalEntryLine deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete JournalEntryLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
