<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\JournalEntry;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * JournalEntryApiController
 * 
 * RESTful API Controller for JournalEntry
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class JournalEntryApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/journal-entries",
     *     summary="Get all JournalEntry records",
     *     tags={"JournalEntry"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $journalEntries = JournalEntry::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $journalEntries->items(),
                'meta' => [
                    'current_page' => $journalEntries->currentPage(),
                    'per_page' => $journalEntries->perPage(),
                    'total' => $journalEntries->total(),
                    'last_page' => $journalEntries->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/journal-entries",
     *     summary="Create a new JournalEntry",
     *     tags={"JournalEntry"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $journalEntry = JournalEntry::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'JournalEntry created successfully',
                'data' => $journalEntry
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create JournalEntry',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/journal-entries/{id}",
     *     summary="Get a specific JournalEntry",
     *     tags={"JournalEntry"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $journalEntry = JournalEntry::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $journalEntry
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'JournalEntry not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/journal-entries/{id}",
     *     summary="Update a JournalEntry",
     *     tags={"JournalEntry"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $journalEntry = JournalEntry::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $journalEntry->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'JournalEntry updated successfully',
                'data' => $journalEntry
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update JournalEntry',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/journal-entries/{id}",
     *     summary="Delete a JournalEntry",
     *     tags={"JournalEntry"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $journalEntry = JournalEntry::findOrFail($id);
            $journalEntry->delete();

            return response()->json([
                'success' => true,
                'message' => 'JournalEntry deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete JournalEntry',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
