<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ManusWebhook;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ManusWebhookApiController
 * 
 * RESTful API Controller for ManusWebhook
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ManusWebhookApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/manus-webhooks",
     *     summary="Get all ManusWebhook records",
     *     tags={"ManusWebhook"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $manusWebhooks = ManusWebhook::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $manusWebhooks->items(),
                'meta' => [
                    'current_page' => $manusWebhooks->currentPage(),
                    'per_page' => $manusWebhooks->perPage(),
                    'total' => $manusWebhooks->total(),
                    'last_page' => $manusWebhooks->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/manus-webhooks",
     *     summary="Create a new ManusWebhook",
     *     tags={"ManusWebhook"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $manusWebhook = ManusWebhook::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ManusWebhook created successfully',
                'data' => $manusWebhook
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ManusWebhook',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/manus-webhooks/{id}",
     *     summary="Get a specific ManusWebhook",
     *     tags={"ManusWebhook"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $manusWebhook = ManusWebhook::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $manusWebhook
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ManusWebhook not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/manus-webhooks/{id}",
     *     summary="Update a ManusWebhook",
     *     tags={"ManusWebhook"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $manusWebhook = ManusWebhook::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $manusWebhook->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ManusWebhook updated successfully',
                'data' => $manusWebhook
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ManusWebhook',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/manus-webhooks/{id}",
     *     summary="Delete a ManusWebhook",
     *     tags={"ManusWebhook"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $manusWebhook = ManusWebhook::findOrFail($id);
            $manusWebhook->delete();

            return response()->json([
                'success' => true,
                'message' => 'ManusWebhook deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ManusWebhook',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
