<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ManusUsageStat;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * ManusUsageStatApiController
 * 
 * RESTful API Controller for ManusUsageStat
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ManusUsageStatApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/manus-usage-stats",
     *     summary="Get all ManusUsageStat records",
     *     tags={"ManusUsageStat"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $manusUsageStats = ManusUsageStat::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $manusUsageStats->items(),
                'meta' => [
                    'current_page' => $manusUsageStats->currentPage(),
                    'per_page' => $manusUsageStats->perPage(),
                    'total' => $manusUsageStats->total(),
                    'last_page' => $manusUsageStats->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/manus-usage-stats",
     *     summary="Create a new ManusUsageStat",
     *     tags={"ManusUsageStat"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $manusUsageStat = ManusUsageStat::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'ManusUsageStat created successfully',
                'data' => $manusUsageStat
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create ManusUsageStat',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/manus-usage-stats/{id}",
     *     summary="Get a specific ManusUsageStat",
     *     tags={"ManusUsageStat"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $manusUsageStat = ManusUsageStat::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $manusUsageStat
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'ManusUsageStat not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/manus-usage-stats/{id}",
     *     summary="Update a ManusUsageStat",
     *     tags={"ManusUsageStat"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $manusUsageStat = ManusUsageStat::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $manusUsageStat->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'ManusUsageStat updated successfully',
                'data' => $manusUsageStat
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update ManusUsageStat',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/manus-usage-stats/{id}",
     *     summary="Delete a ManusUsageStat",
     *     tags={"ManusUsageStat"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $manusUsageStat = ManusUsageStat::findOrFail($id);
            $manusUsageStat->delete();

            return response()->json([
                'success' => true,
                'message' => 'ManusUsageStat deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete ManusUsageStat',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
