<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\MedicalInsurance;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * MedicalInsuranceApiController
 * 
 * RESTful API Controller for MedicalInsurance
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class MedicalInsuranceApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/medical-insurances",
     *     summary="Get all MedicalInsurance records",
     *     tags={"MedicalInsurance"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $medicalInsurances = MedicalInsurance::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $medicalInsurances->items(),
                'meta' => [
                    'current_page' => $medicalInsurances->currentPage(),
                    'per_page' => $medicalInsurances->perPage(),
                    'total' => $medicalInsurances->total(),
                    'last_page' => $medicalInsurances->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/medical-insurances",
     *     summary="Create a new MedicalInsurance",
     *     tags={"MedicalInsurance"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $medicalInsurance = MedicalInsurance::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'MedicalInsurance created successfully',
                'data' => $medicalInsurance
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create MedicalInsurance',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/medical-insurances/{id}",
     *     summary="Get a specific MedicalInsurance",
     *     tags={"MedicalInsurance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $medicalInsurance = MedicalInsurance::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $medicalInsurance
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'MedicalInsurance not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/medical-insurances/{id}",
     *     summary="Update a MedicalInsurance",
     *     tags={"MedicalInsurance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $medicalInsurance = MedicalInsurance::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $medicalInsurance->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'MedicalInsurance updated successfully',
                'data' => $medicalInsurance
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update MedicalInsurance',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/medical-insurances/{id}",
     *     summary="Delete a MedicalInsurance",
     *     tags={"MedicalInsurance"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $medicalInsurance = MedicalInsurance::findOrFail($id);
            $medicalInsurance->delete();

            return response()->json([
                'success' => true,
                'message' => 'MedicalInsurance deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete MedicalInsurance',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
