<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\PaymentMethod;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * PaymentMethodApiController
 * 
 * RESTful API Controller for PaymentMethod
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class PaymentMethodApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/payment-methods",
     *     summary="Get all PaymentMethod records",
     *     tags={"PaymentMethod"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $paymentMethods = PaymentMethod::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $paymentMethods->items(),
                'meta' => [
                    'current_page' => $paymentMethods->currentPage(),
                    'per_page' => $paymentMethods->perPage(),
                    'total' => $paymentMethods->total(),
                    'last_page' => $paymentMethods->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/payment-methods",
     *     summary="Create a new PaymentMethod",
     *     tags={"PaymentMethod"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $paymentMethod = PaymentMethod::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'PaymentMethod created successfully',
                'data' => $paymentMethod
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create PaymentMethod',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/payment-methods/{id}",
     *     summary="Get a specific PaymentMethod",
     *     tags={"PaymentMethod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $paymentMethod = PaymentMethod::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $paymentMethod
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'PaymentMethod not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/payment-methods/{id}",
     *     summary="Update a PaymentMethod",
     *     tags={"PaymentMethod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $paymentMethod = PaymentMethod::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $paymentMethod->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'PaymentMethod updated successfully',
                'data' => $paymentMethod
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update PaymentMethod',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/payment-methods/{id}",
     *     summary="Delete a PaymentMethod",
     *     tags={"PaymentMethod"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $paymentMethod = PaymentMethod::findOrFail($id);
            $paymentMethod->delete();

            return response()->json([
                'success' => true,
                'message' => 'PaymentMethod deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete PaymentMethod',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
