<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\PurchaseInvoiceLine;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * PurchaseInvoiceLineApiController
 * 
 * RESTful API Controller for PurchaseInvoiceLine
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class PurchaseInvoiceLineApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/purchase-invoice-lines",
     *     summary="Get all PurchaseInvoiceLine records",
     *     tags={"PurchaseInvoiceLine"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $purchaseInvoiceLines = PurchaseInvoiceLine::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $purchaseInvoiceLines->items(),
                'meta' => [
                    'current_page' => $purchaseInvoiceLines->currentPage(),
                    'per_page' => $purchaseInvoiceLines->perPage(),
                    'total' => $purchaseInvoiceLines->total(),
                    'last_page' => $purchaseInvoiceLines->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/purchase-invoice-lines",
     *     summary="Create a new PurchaseInvoiceLine",
     *     tags={"PurchaseInvoiceLine"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $purchaseInvoiceLine = PurchaseInvoiceLine::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'PurchaseInvoiceLine created successfully',
                'data' => $purchaseInvoiceLine
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create PurchaseInvoiceLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/purchase-invoice-lines/{id}",
     *     summary="Get a specific PurchaseInvoiceLine",
     *     tags={"PurchaseInvoiceLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $purchaseInvoiceLine = PurchaseInvoiceLine::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $purchaseInvoiceLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'PurchaseInvoiceLine not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/purchase-invoice-lines/{id}",
     *     summary="Update a PurchaseInvoiceLine",
     *     tags={"PurchaseInvoiceLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $purchaseInvoiceLine = PurchaseInvoiceLine::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $purchaseInvoiceLine->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'PurchaseInvoiceLine updated successfully',
                'data' => $purchaseInvoiceLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update PurchaseInvoiceLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/purchase-invoice-lines/{id}",
     *     summary="Delete a PurchaseInvoiceLine",
     *     tags={"PurchaseInvoiceLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $purchaseInvoiceLine = PurchaseInvoiceLine::findOrFail($id);
            $purchaseInvoiceLine->delete();

            return response()->json([
                'success' => true,
                'message' => 'PurchaseInvoiceLine deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete PurchaseInvoiceLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
