<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\PurchaseReturn;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * PurchaseReturnApiController
 * 
 * RESTful API Controller for PurchaseReturn
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class PurchaseReturnApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/purchase-returns",
     *     summary="Get all PurchaseReturn records",
     *     tags={"PurchaseReturn"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $purchaseReturns = PurchaseReturn::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $purchaseReturns->items(),
                'meta' => [
                    'current_page' => $purchaseReturns->currentPage(),
                    'per_page' => $purchaseReturns->perPage(),
                    'total' => $purchaseReturns->total(),
                    'last_page' => $purchaseReturns->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/purchase-returns",
     *     summary="Create a new PurchaseReturn",
     *     tags={"PurchaseReturn"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $purchaseReturn = PurchaseReturn::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'PurchaseReturn created successfully',
                'data' => $purchaseReturn
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create PurchaseReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/purchase-returns/{id}",
     *     summary="Get a specific PurchaseReturn",
     *     tags={"PurchaseReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $purchaseReturn = PurchaseReturn::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $purchaseReturn
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'PurchaseReturn not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/purchase-returns/{id}",
     *     summary="Update a PurchaseReturn",
     *     tags={"PurchaseReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $purchaseReturn = PurchaseReturn::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $purchaseReturn->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'PurchaseReturn updated successfully',
                'data' => $purchaseReturn
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update PurchaseReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/purchase-returns/{id}",
     *     summary="Delete a PurchaseReturn",
     *     tags={"PurchaseReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $purchaseReturn = PurchaseReturn::findOrFail($id);
            $purchaseReturn->delete();

            return response()->json([
                'success' => true,
                'message' => 'PurchaseReturn deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete PurchaseReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
