<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\RolePermission;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * RolePermissionApiController
 * 
 * RESTful API Controller for RolePermission
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class RolePermissionApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/role-permissions",
     *     summary="Get all RolePermission records",
     *     tags={"RolePermission"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $rolePermissions = RolePermission::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $rolePermissions->items(),
                'meta' => [
                    'current_page' => $rolePermissions->currentPage(),
                    'per_page' => $rolePermissions->perPage(),
                    'total' => $rolePermissions->total(),
                    'last_page' => $rolePermissions->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/role-permissions",
     *     summary="Create a new RolePermission",
     *     tags={"RolePermission"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $rolePermission = RolePermission::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'RolePermission created successfully',
                'data' => $rolePermission
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create RolePermission',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/role-permissions/{id}",
     *     summary="Get a specific RolePermission",
     *     tags={"RolePermission"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $rolePermission = RolePermission::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $rolePermission
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'RolePermission not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/role-permissions/{id}",
     *     summary="Update a RolePermission",
     *     tags={"RolePermission"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $rolePermission = RolePermission::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $rolePermission->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'RolePermission updated successfully',
                'data' => $rolePermission
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update RolePermission',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/role-permissions/{id}",
     *     summary="Delete a RolePermission",
     *     tags={"RolePermission"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $rolePermission = RolePermission::findOrFail($id);
            $rolePermission->delete();

            return response()->json([
                'success' => true,
                'message' => 'RolePermission deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete RolePermission',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
