<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\SalesOrderLine;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * SalesOrderLineApiController
 * 
 * RESTful API Controller for SalesOrderLine
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class SalesOrderLineApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/sales-order-lines",
     *     summary="Get all SalesOrderLine records",
     *     tags={"SalesOrderLine"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $salesOrderLines = SalesOrderLine::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $salesOrderLines->items(),
                'meta' => [
                    'current_page' => $salesOrderLines->currentPage(),
                    'per_page' => $salesOrderLines->perPage(),
                    'total' => $salesOrderLines->total(),
                    'last_page' => $salesOrderLines->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/sales-order-lines",
     *     summary="Create a new SalesOrderLine",
     *     tags={"SalesOrderLine"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesOrderLine = SalesOrderLine::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesOrderLine created successfully',
                'data' => $salesOrderLine
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create SalesOrderLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/sales-order-lines/{id}",
     *     summary="Get a specific SalesOrderLine",
     *     tags={"SalesOrderLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $salesOrderLine = SalesOrderLine::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $salesOrderLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'SalesOrderLine not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/sales-order-lines/{id}",
     *     summary="Update a SalesOrderLine",
     *     tags={"SalesOrderLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $salesOrderLine = SalesOrderLine::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesOrderLine->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesOrderLine updated successfully',
                'data' => $salesOrderLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update SalesOrderLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/sales-order-lines/{id}",
     *     summary="Delete a SalesOrderLine",
     *     tags={"SalesOrderLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $salesOrderLine = SalesOrderLine::findOrFail($id);
            $salesOrderLine->delete();

            return response()->json([
                'success' => true,
                'message' => 'SalesOrderLine deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete SalesOrderLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
