<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\SalesInvoice;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * SalesInvoiceApiController
 * 
 * RESTful API Controller for SalesInvoice
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class SalesInvoiceApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/sales-invoices",
     *     summary="Get all SalesInvoice records",
     *     tags={"SalesInvoice"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $salesInvoices = SalesInvoice::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $salesInvoices->items(),
                'meta' => [
                    'current_page' => $salesInvoices->currentPage(),
                    'per_page' => $salesInvoices->perPage(),
                    'total' => $salesInvoices->total(),
                    'last_page' => $salesInvoices->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/sales-invoices",
     *     summary="Create a new SalesInvoice",
     *     tags={"SalesInvoice"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesInvoice = SalesInvoice::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesInvoice created successfully',
                'data' => $salesInvoice
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create SalesInvoice',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/sales-invoices/{id}",
     *     summary="Get a specific SalesInvoice",
     *     tags={"SalesInvoice"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $salesInvoice = SalesInvoice::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $salesInvoice
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'SalesInvoice not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/sales-invoices/{id}",
     *     summary="Update a SalesInvoice",
     *     tags={"SalesInvoice"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $salesInvoice = SalesInvoice::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesInvoice->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesInvoice updated successfully',
                'data' => $salesInvoice
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update SalesInvoice',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/sales-invoices/{id}",
     *     summary="Delete a SalesInvoice",
     *     tags={"SalesInvoice"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $salesInvoice = SalesInvoice::findOrFail($id);
            $salesInvoice->delete();

            return response()->json([
                'success' => true,
                'message' => 'SalesInvoice deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete SalesInvoice',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
