<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\SalesOrder;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * SalesOrderApiController
 * 
 * RESTful API Controller for SalesOrder
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class SalesOrderApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/sales-orders",
     *     summary="Get all SalesOrder records",
     *     tags={"SalesOrder"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $salesOrders = SalesOrder::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $salesOrders->items(),
                'meta' => [
                    'current_page' => $salesOrders->currentPage(),
                    'per_page' => $salesOrders->perPage(),
                    'total' => $salesOrders->total(),
                    'last_page' => $salesOrders->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/sales-orders",
     *     summary="Create a new SalesOrder",
     *     tags={"SalesOrder"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesOrder = SalesOrder::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesOrder created successfully',
                'data' => $salesOrder
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create SalesOrder',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/sales-orders/{id}",
     *     summary="Get a specific SalesOrder",
     *     tags={"SalesOrder"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $salesOrder = SalesOrder::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $salesOrder
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'SalesOrder not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/sales-orders/{id}",
     *     summary="Update a SalesOrder",
     *     tags={"SalesOrder"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $salesOrder = SalesOrder::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesOrder->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesOrder updated successfully',
                'data' => $salesOrder
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update SalesOrder',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/sales-orders/{id}",
     *     summary="Delete a SalesOrder",
     *     tags={"SalesOrder"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $salesOrder = SalesOrder::findOrFail($id);
            $salesOrder->delete();

            return response()->json([
                'success' => true,
                'message' => 'SalesOrder deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete SalesOrder',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
