<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\SalesReturn;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * SalesReturnApiController
 * 
 * RESTful API Controller for SalesReturn
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class SalesReturnApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/sales-returns",
     *     summary="Get all SalesReturn records",
     *     tags={"SalesReturn"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $salesReturns = SalesReturn::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $salesReturns->items(),
                'meta' => [
                    'current_page' => $salesReturns->currentPage(),
                    'per_page' => $salesReturns->perPage(),
                    'total' => $salesReturns->total(),
                    'last_page' => $salesReturns->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/sales-returns",
     *     summary="Create a new SalesReturn",
     *     tags={"SalesReturn"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesReturn = SalesReturn::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesReturn created successfully',
                'data' => $salesReturn
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create SalesReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/sales-returns/{id}",
     *     summary="Get a specific SalesReturn",
     *     tags={"SalesReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $salesReturn = SalesReturn::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $salesReturn
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'SalesReturn not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/sales-returns/{id}",
     *     summary="Update a SalesReturn",
     *     tags={"SalesReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $salesReturn = SalesReturn::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $salesReturn->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'SalesReturn updated successfully',
                'data' => $salesReturn
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update SalesReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/sales-returns/{id}",
     *     summary="Delete a SalesReturn",
     *     tags={"SalesReturn"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $salesReturn = SalesReturn::findOrFail($id);
            $salesReturn->delete();

            return response()->json([
                'success' => true,
                'message' => 'SalesReturn deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete SalesReturn',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
