<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Sector;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * SectorApiController
 * 
 * RESTful API Controller for Sector
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class SectorApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/sectors",
     *     summary="Get all Sector records",
     *     tags={"Sector"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $sectors = Sector::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $sectors->items(),
                'meta' => [
                    'current_page' => $sectors->currentPage(),
                    'per_page' => $sectors->perPage(),
                    'total' => $sectors->total(),
                    'last_page' => $sectors->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/sectors",
     *     summary="Create a new Sector",
     *     tags={"Sector"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $sector = Sector::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'Sector created successfully',
                'data' => $sector
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create Sector',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/sectors/{id}",
     *     summary="Get a specific Sector",
     *     tags={"Sector"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $sector = Sector::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $sector
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Sector not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/sectors/{id}",
     *     summary="Update a Sector",
     *     tags={"Sector"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $sector = Sector::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $sector->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'Sector updated successfully',
                'data' => $sector
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update Sector',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/sectors/{id}",
     *     summary="Delete a Sector",
     *     tags={"Sector"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $sector = Sector::findOrFail($id);
            $sector->delete();

            return response()->json([
                'success' => true,
                'message' => 'Sector deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete Sector',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
