<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\StockCountLine;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * StockCountLineApiController
 * 
 * RESTful API Controller for StockCountLine
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class StockCountLineApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/stock-count-lines",
     *     summary="Get all StockCountLine records",
     *     tags={"StockCountLine"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $stockCountLines = StockCountLine::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $stockCountLines->items(),
                'meta' => [
                    'current_page' => $stockCountLines->currentPage(),
                    'per_page' => $stockCountLines->perPage(),
                    'total' => $stockCountLines->total(),
                    'last_page' => $stockCountLines->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/stock-count-lines",
     *     summary="Create a new StockCountLine",
     *     tags={"StockCountLine"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $stockCountLine = StockCountLine::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'StockCountLine created successfully',
                'data' => $stockCountLine
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create StockCountLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/stock-count-lines/{id}",
     *     summary="Get a specific StockCountLine",
     *     tags={"StockCountLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $stockCountLine = StockCountLine::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $stockCountLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'StockCountLine not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/stock-count-lines/{id}",
     *     summary="Update a StockCountLine",
     *     tags={"StockCountLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $stockCountLine = StockCountLine::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $stockCountLine->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'StockCountLine updated successfully',
                'data' => $stockCountLine
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update StockCountLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/stock-count-lines/{id}",
     *     summary="Delete a StockCountLine",
     *     tags={"StockCountLine"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $stockCountLine = StockCountLine::findOrFail($id);
            $stockCountLine->delete();

            return response()->json([
                'success' => true,
                'message' => 'StockCountLine deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete StockCountLine',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
