<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Vault;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * VaultApiController
 * 
 * RESTful API Controller for Vault
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class VaultApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/vaults",
     *     summary="Get all Vault records",
     *     tags={"Vault"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $vaults = Vault::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $vaults->items(),
                'meta' => [
                    'current_page' => $vaults->currentPage(),
                    'per_page' => $vaults->perPage(),
                    'total' => $vaults->total(),
                    'last_page' => $vaults->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/vaults",
     *     summary="Create a new Vault",
     *     tags={"Vault"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $vault = Vault::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'Vault created successfully',
                'data' => $vault
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create Vault',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/vaults/{id}",
     *     summary="Get a specific Vault",
     *     tags={"Vault"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $vault = Vault::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $vault
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Vault not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/vaults/{id}",
     *     summary="Update a Vault",
     *     tags={"Vault"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $vault = Vault::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $vault->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'Vault updated successfully',
                'data' => $vault
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update Vault',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/vaults/{id}",
     *     summary="Delete a Vault",
     *     tags={"Vault"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $vault = Vault::findOrFail($id);
            $vault->delete();

            return response()->json([
                'success' => true,
                'message' => 'Vault deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete Vault',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
