<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\WeightedItem;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

/**
 * WeightedItemApiController
 * 
 * RESTful API Controller for WeightedItem
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class WeightedItemApiController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @OA\Get(
     *     path="/api/weighted-items",
     *     summary="Get all WeightedItem records",
     *     tags={"WeightedItem"},
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {
        try {
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            $weightedItems = WeightedItem::query()
                ->when($request->has('search'), function ($query) use ($request) {
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{$search}%");
                })
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => $weightedItems->items(),
                'meta' => [
                    'current_page' => $weightedItems->currentPage(),
                    'per_page' => $weightedItems->perPage(),
                    'total' => $weightedItems->total(),
                    'last_page' => $weightedItems->lastPage(),
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\Post(
     *     path="/api/weighted-items",
     *     summary="Create a new WeightedItem",
     *     tags={"WeightedItem"},
     *     @OA\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $weightedItem = WeightedItem::create($validated);

            return response()->json([
                'success' => true,
                'message' => 'WeightedItem created successfully',
                'data' => $weightedItem
            ], 201);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create WeightedItem',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     * 
     * @OA\Get(
     *     path="/api/weighted-items/{id}",
     *     summary="Get a specific WeightedItem",
     *     tags={"WeightedItem"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {
        try {
            $weightedItem = WeightedItem::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => $weightedItem
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'WeightedItem not found',
                'error' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     * 
     * @OA\Put(
     *     path="/api/weighted-items/{id}",
     *     summary="Update a WeightedItem",
     *     tags={"WeightedItem"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $weightedItem = WeightedItem::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            $weightedItem->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'WeightedItem updated successfully',
                'data' => $weightedItem
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to update WeightedItem',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\Delete(
     *     path="/api/weighted-items/{id}",
     *     summary="Delete a WeightedItem",
     *     tags={"WeightedItem"},
     *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
     *     @OA\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {
        try {
            $weightedItem = WeightedItem::findOrFail($id);
            $weightedItem->delete();

            return response()->json([
                'success' => true,
                'message' => 'WeightedItem deleted successfully'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete WeightedItem',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
