<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * API Logging Middleware
 * 
 * Logs all API requests and responses for auditing
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ApiLoggingMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $startTime = microtime(true);

        // Process the request
        $response = $next($request);

        $endTime = microtime(true);
        $duration = round(($endTime - $startTime) * 1000, 2); // in milliseconds

        // Log the API request
        $this->logApiRequest($request, $response, $duration);

        return $response;
    }

    /**
     * Log API request details
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $response
     * @param  float  $duration
     * @return void
     */
    protected function logApiRequest(Request $request, $response, float $duration): void
    {
        try {
            $logData = [
                'method' => $request->method(),
                'url' => $request->fullUrl(),
                'path' => $request->path(),
                'ip_address' => $request->ip(),
                'user_agent' => $request->userAgent(),
                'request_headers' => json_encode($this->sanitizeHeaders($request->headers->all())),
                'request_body' => json_encode($this->sanitizeRequestBody($request->all())),
                'response_status' => $response->status(),
                'response_body' => $this->getResponseBody($response),
                'duration_ms' => $duration,
                'created_at' => now(),
                'updated_at' => now()
            ];

            // Try to save to database
            try {
                DB::table('api_logs')->insert($logData);
            } catch (\Exception $e) {
                // If database insert fails, log to file instead
                Log::channel('api')->info('API Request', $logData);
            }

        } catch (\Exception $e) {
            Log::error('Failed to log API request', [
                'error' => $e->getMessage(),
                'url' => $request->fullUrl()
            ]);
        }
    }

    /**
     * Sanitize headers to remove sensitive information
     *
     * @param  array  $headers
     * @return array
     */
    protected function sanitizeHeaders(array $headers): array
    {
        $sensitiveHeaders = ['authorization', 'x-api-token', 'cookie'];
        
        foreach ($sensitiveHeaders as $header) {
            if (isset($headers[$header])) {
                $headers[$header] = ['***REDACTED***'];
            }
        }

        return $headers;
    }

    /**
     * Sanitize request body to remove sensitive information
     *
     * @param  array  $data
     * @return array
     */
    protected function sanitizeRequestBody(array $data): array
    {
        $sensitiveFields = ['password', 'password_confirmation', 'token', 'secret', 'api_key'];
        
        foreach ($sensitiveFields as $field) {
            if (isset($data[$field])) {
                $data[$field] = '***REDACTED***';
            }
        }

        return $data;
    }

    /**
     * Get response body as string
     *
     * @param  mixed  $response
     * @return string|null
     */
    protected function getResponseBody($response): ?string
    {
        try {
            $content = $response->getContent();
            
            // Limit response body size to prevent large logs
            if (strlen($content) > 10000) {
                return substr($content, 0, 10000) . '... [TRUNCATED]';
            }

            return $content;
        } catch (\Exception $e) {
            return null;
        }
    }
}
