<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

/**
 * API Permission Middleware
 * 
 * Handles API permission checking and authorization
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ApiPermissionMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string  $permission
     * @return mixed
     */
    public function handle(Request $request, Closure $next, string $permission = null)
    {
        // Get authenticated user from request
        $user = $request->get('authenticated_user');

        if (!$user) {
            return response()->json([
                'success' => false,
                'message' => 'Authentication required',
                'error' => 'User not authenticated'
            ], 401);
        }

        // If no specific permission is required, allow access
        if (!$permission) {
            return $next($request);
        }

        // Check if user has the required permission
        if (!$this->hasPermission($user, $permission)) {
            Log::warning('Permission denied', [
                'user_id' => $user->id ?? null,
                'permission' => $permission,
                'route' => $request->path()
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Permission denied',
                'error' => "You don't have permission to access this resource",
                'required_permission' => $permission
            ], 403);
        }

        return $next($request);
    }

    /**
     * Check if user has the required permission
     *
     * @param  mixed  $user
     * @param  string  $permission
     * @return bool
     */
    protected function hasPermission($user, string $permission): bool
    {
        // TODO: Implement actual permission checking logic
        // Example using Spatie Laravel Permission:
        // return $user->hasPermissionTo($permission);
        
        // For now, return true to allow all authenticated users
        return true;
    }
}
