<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

/**
 * API Rate Limit Middleware
 * 
 * Implements rate limiting for API endpoints
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date 2025-12-03
 */
class ApiRateLimitMiddleware
{
    /**
     * Maximum requests per minute
     */
    protected int $maxAttempts = 60;

    /**
     * Time window in minutes
     */
    protected int $decayMinutes = 1;

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $key = $this->resolveRequestSignature($request);

        $attempts = Cache::get($key, 0);

        if ($attempts >= $this->maxAttempts) {
            return response()->json([
                'success' => false,
                'message' => 'Too many requests',
                'error' => 'Rate limit exceeded. Please try again later.',
                'retry_after' => $this->decayMinutes * 60
            ], 429);
        }

        Cache::put($key, $attempts + 1, now()->addMinutes($this->decayMinutes));

        $response = $next($request);

        // Add rate limit headers
        $response->headers->set('X-RateLimit-Limit', $this->maxAttempts);
        $response->headers->set('X-RateLimit-Remaining', max(0, $this->maxAttempts - $attempts - 1));

        return $response;
    }

    /**
     * Resolve request signature for rate limiting
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string
     */
    protected function resolveRequestSignature(Request $request): string
    {
        // Use IP address and API token (if available) as signature
        $token = $request->header('X-API-Token', 'anonymous');
        $ip = $request->ip();
        
        return 'rate_limit:' . sha1($ip . '|' . $token);
    }
}
