php: "8.2"
env: production

deploy:
  - echo "🚀 Deploying PHP Magic System - Developer Branch"
  - php artisan migrate --force 2>&1 || true
  - php artisan cache:clear
  - php artisan config:clear  
  - php artisan view:clear
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - echo "✅ Deployment completed successfully!"
