php: "8.2"
env: production

deploy:
  - echo "🚀 Deploying PHP Magic System - Developer Branch"
  - echo "📦 Running database migrations..."
  - php artisan migrate --force
  - echo "✅ Migrations completed successfully!"
  - echo "🧹 Clearing caches..."
  - php artisan cache:clear
  - php artisan config:clear  
  - php artisan view:clear
  - echo "⚡ Optimizing application..."
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - echo "✅ Deployment completed successfully!"
