#!/usr/bin/env python3
"""
API Generator v3.16.0
Auto-generates RESTful API for all Laravel models

@version 3.16.0
@author SEMOP Team
@date 2025-12-03
"""

import os
import re
from pathlib import Path
from datetime import datetime


class ApiGenerator:
    def __init__(self, base_path):
        self.base_path = Path(base_path)
        self.models_path = self.base_path / 'app' / 'Models'
        self.controllers_path = self.base_path / 'app' / 'Http' / 'Controllers' / 'Api'
        self.routes_path = self.base_path / 'routes'
        
        self.models = []
        self.generated_controllers = []
        self.stats = {
            'models_found': 0,
            'controllers_generated': 0,
            'routes_generated': 0,
            'errors': []
        }
    
    def log(self, message):
        """Print log message"""
        print(f"[API Generator] {message}")
    
    def discover_models(self):
        """Discover all PHP models in the project"""
        self.log('اكتشاف النماذج...')
        
        for php_file in self.models_path.rglob('*.php'):
            relative_path = php_file.relative_to(self.models_path)
            class_name = str(relative_path.with_suffix('')).replace(os.sep, '\\')
            base_name = php_file.stem
            
            self.models.append({
                'name': class_name,
                'base_name': base_name,
                'file_path': str(php_file),
                'full_class': f'App\\Models\\{class_name}'
            })
        
        self.stats['models_found'] = len(self.models)
        self.log(f"تم اكتشاف {self.stats['models_found']} نموذج")
    
    def to_kebab_case(self, text):
        """Convert text to kebab-case"""
        # Insert hyphen before uppercase letters
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1-\2', text)
        # Insert hyphen before uppercase letters preceded by lowercase
        return re.sub('([a-z0-9])([A-Z])', r'\1-\2', s1).lower()
    
    def to_camel_case(self, text):
        """Convert text to camelCase"""
        return text[0].lower() + text[1:] if text else text
    
    def pluralize(self, text):
        """Simple pluralization"""
        if text.endswith('y'):
            return text[:-1] + 'ies'
        elif text.endswith('s'):
            return text + 'es'
        else:
            return text + 's'
    
    def generate_controller_content(self, model):
        """Generate controller content for a model"""
        base_name = model['base_name']
        model_class = model['full_class']
        controller_name = f"{base_name}ApiController"
        resource_name = self.to_kebab_case(self.pluralize(base_name))
        variable_name = self.to_camel_case(base_name)
        plural_variable = self.to_camel_case(self.pluralize(base_name))
        today = datetime.now().strftime('%Y-%m-%d')
        
        return f'''<?php

namespace App\\Http\\Controllers\\Api;

use App\\Http\\Controllers\\Controller;
use {model_class};
use Illuminate\\Http\\Request;
use Illuminate\\Http\\JsonResponse;

/**
 * {controller_name}
 * 
 * RESTful API Controller for {base_name}
 * Auto-generated by API Generator v3.16.0
 * 
 * @version 3.16.0
 * @date {today}
 */
class {controller_name} extends Controller
{{
    /**
     * Display a listing of the resource.
     * 
     * @OA\\Get(
     *     path="/api/{resource_name}",
     *     summary="Get all {base_name} records",
     *     tags={{"{base_name}"}},
     *     @OA\\Response(response=200, description="Success")
     * )
     */
    public function index(Request $request): JsonResponse
    {{
        try {{
            $perPage = $request->get('per_page', 15);
            $page = $request->get('page', 1);
            
            ${plural_variable} = {base_name}::query()
                ->when($request->has('search'), function ($query) use ($request) {{
                    $search = $request->get('search');
                    // Add searchable fields here
                    return $query->where('id', 'like', "%{{$search}}%");
                }})
                ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'success' => true,
                'data' => ${plural_variable}->items(),
                'meta' => [
                    'current_page' => ${plural_variable}->currentPage(),
                    'per_page' => ${plural_variable}->perPage(),
                    'total' => ${plural_variable}->total(),
                    'last_page' => ${plural_variable}->lastPage(),
                ]
            ]);
        }} catch (\\Exception $e) {{
            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve records',
                'error' => $e->getMessage()
            ], 500);
        }}
    }}

    /**
     * Store a newly created resource in storage.
     * 
     * @OA\\Post(
     *     path="/api/{resource_name}",
     *     summary="Create a new {base_name}",
     *     tags={{"{base_name}"}},
     *     @OA\\Response(response=201, description="Created")
     * )
     */
    public function store(Request $request): JsonResponse
    {{
        try {{
            $validated = $request->validate([
                // Add validation rules here
            ]);

            ${variable_name} = {base_name}::create($validated);

            return response()->json([
                'success' => true,
                'message' => '{base_name} created successfully',
                'data' => ${variable_name}
            ], 201);
        }} catch (\\Exception $e) {{
            return response()->json([
                'success' => false,
                'message' => 'Failed to create {base_name}',
                'error' => $e->getMessage()
            ], 500);
        }}
    }}

    /**
     * Display the specified resource.
     * 
     * @OA\\Get(
     *     path="/api/{resource_name}/{{id}}",
     *     summary="Get a specific {base_name}",
     *     tags={{"{base_name}"}},
     *     @OA\\Parameter(name="id", in="path", required=true, @OA\\Schema(type="integer")),
     *     @OA\\Response(response=200, description="Success")
     * )
     */
    public function show($id): JsonResponse
    {{
        try {{
            ${variable_name} = {base_name}::findOrFail($id);

            return response()->json([
                'success' => true,
                'data' => ${variable_name}
            ]);
        }} catch (\\Exception $e) {{
            return response()->json([
                'success' => false,
                'message' => '{base_name} not found',
                'error' => $e->getMessage()
            ], 404);
        }}
    }}

    /**
     * Update the specified resource in storage.
     * 
     * @OA\\Put(
     *     path="/api/{resource_name}/{{id}}",
     *     summary="Update a {base_name}",
     *     tags={{"{base_name}"}},
     *     @OA\\Parameter(name="id", in="path", required=true, @OA\\Schema(type="integer")),
     *     @OA\\Response(response=200, description="Success")
     * )
     */
    public function update(Request $request, $id): JsonResponse
    {{
        try {{
            ${variable_name} = {base_name}::findOrFail($id);
            
            $validated = $request->validate([
                // Add validation rules here
            ]);

            ${variable_name}->update($validated);

            return response()->json([
                'success' => true,
                'message' => '{base_name} updated successfully',
                'data' => ${variable_name}
            ]);
        }} catch (\\Exception $e) {{
            return response()->json([
                'success' => false,
                'message' => 'Failed to update {base_name}',
                'error' => $e->getMessage()
            ], 500);
        }}
    }}

    /**
     * Remove the specified resource from storage.
     * 
     * @OA\\Delete(
     *     path="/api/{resource_name}/{{id}}",
     *     summary="Delete a {base_name}",
     *     tags={{"{base_name}"}},
     *     @OA\\Parameter(name="id", in="path", required=true, @OA\\Schema(type="integer")),
     *     @OA\\Response(response=200, description="Success")
     * )
     */
    public function destroy($id): JsonResponse
    {{
        try {{
            ${variable_name} = {base_name}::findOrFail($id);
            ${variable_name}->delete();

            return response()->json([
                'success' => true,
                'message' => '{base_name} deleted successfully'
            ]);
        }} catch (\\Exception $e) {{
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete {base_name}',
                'error' => $e->getMessage()
            ], 500);
        }}
    }}
}}
'''
    
    def generate_controllers(self):
        """Generate controllers for all models"""
        self.log('توليد Controllers...')
        
        # Create controllers directory if it doesn't exist
        self.controllers_path.mkdir(parents=True, exist_ok=True)
        
        for model in self.models:
            try:
                base_name = model['base_name']
                controller_name = f"{base_name}ApiController"
                controller_file = self.controllers_path / f"{controller_name}.php"
                
                # Skip if already exists
                if controller_file.exists():
                    self.log(f"تخطي {controller_name} - موجود بالفعل")
                    continue
                
                content = self.generate_controller_content(model)
                controller_file.write_text(content, encoding='utf-8')
                
                self.generated_controllers.append({
                    'name': controller_name,
                    'path': str(controller_file),
                    'model': base_name
                })
                
                self.stats['controllers_generated'] += 1
                self.log(f"تم توليد {controller_name}")
                
            except Exception as e:
                error_msg = f"فشل توليد Controller لـ {model['base_name']}: {str(e)}"
                self.stats['errors'].append(error_msg)
                self.log(f"خطأ: {error_msg}")
        
        self.log(f"تم توليد {self.stats['controllers_generated']} Controller")
    
    def generate_routes_content(self):
        """Generate routes file content"""
        today = datetime.now().strftime('%Y-%m-%d')
        
        content = f'''<?php

use Illuminate\\Support\\Facades\\Route;

/*
|--------------------------------------------------------------------------
| Auto-Generated API Routes
|--------------------------------------------------------------------------
| Version: 3.16.0
| Generated: {today}
| Total Models: {self.stats['models_found']}
|
| This file was automatically generated by API Generator v3.16.0
| DO NOT EDIT THIS FILE MANUALLY
*/

'''
        
        for model in self.models:
            base_name = model['base_name']
            controller_name = f"{base_name}ApiController"
            resource_name = self.to_kebab_case(self.pluralize(base_name))
            
            content += f'''
// {base_name} API Routes
Route::prefix('{resource_name}')->group(function () {{
    Route::get('/', [App\\Http\\Controllers\\Api\\{controller_name}::class, 'index']);
    Route::post('/', [App\\Http\\Controllers\\Api\\{controller_name}::class, 'store']);
    Route::get('/{{id}}', [App\\Http\\Controllers\\Api\\{controller_name}::class, 'show']);
    Route::put('/{{id}}', [App\\Http\\Controllers\\Api\\{controller_name}::class, 'update']);
    Route::delete('/{{id}}', [App\\Http\\Controllers\\Api\\{controller_name}::class, 'destroy']);
}});
'''
        
        return content
    
    def generate_routes(self):
        """Generate routes file"""
        self.log('توليد Routes...')
        
        routes_file = self.routes_path / 'api_generated.php'
        content = self.generate_routes_content()
        
        routes_file.write_text(content, encoding='utf-8')
        self.stats['routes_generated'] = len(self.models)
        
        self.log(f"تم توليد ملف Routes: api_generated.php")
    
    def generate_documentation(self):
        """Generate documentation report"""
        self.log('توليد التوثيق...')
        
        today = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Generate models list
        models_list = ''
        for model in self.models:
            base_name = model['base_name']
            resource_name = self.to_kebab_case(self.pluralize(base_name))
            models_list += f"- **{base_name}**: `/api/{resource_name}`\\n"
        
        # Generate errors list
        errors_section = ''
        if self.stats['errors']:
            errors_section = "## ⚠️ الأخطاء\\n\\n"
            for error in self.stats['errors']:
                errors_section += f"- {error}\\n"
        
        content = f'''# 🚀 API Generator v3.16.0 - تقرير التوليد

**التاريخ:** {today}  
**الإصدار:** 3.16.0  
**المشروع:** php-magic-system (SEMOP)

---

## 📊 الإحصائيات

| المؤشر | القيمة |
|--------|--------|
| النماذج المكتشفة | {self.stats['models_found']} |
| Controllers المولدة | {self.stats['controllers_generated']} |
| Routes المولدة | {self.stats['routes_generated']} |
| الأخطاء | {len(self.stats['errors'])} |

---

## 📋 النماذج والـ API Endpoints

{models_list}

---

## 🎯 الميزات المولدة

### 1. RESTful Controllers
تم توليد Controllers كاملة لجميع النماذج في:
```
app/Http/Controllers/Api/
```

كل Controller يحتوي على:
- `index()` - عرض جميع السجلات مع pagination
- `store()` - إنشاء سجل جديد
- `show()` - عرض سجل محدد
- `update()` - تحديث سجل
- `destroy()` - حذف سجل

### 2. Routes
تم توليد ملف Routes شامل:
```
routes/api_generated.php
```

### 3. OpenAPI Documentation
تم إضافة تعليقات OpenAPI (Swagger) لجميع الـ endpoints.

---

## 🔧 التكامل

### إضافة Routes إلى المشروع

أضف السطر التالي إلى `routes/api.php`:

```php
require __DIR__.'/api_generated.php';
```

---

## 📖 استخدام API

### مثال: الحصول على جميع المستخدمين

```bash
GET /api/users
```

**Response:**
```json
{{
    "success": true,
    "data": [...],
    "meta": {{
        "current_page": 1,
        "per_page": 15,
        "total": 100,
        "last_page": 7
    }}
}}
```

### مثال: إنشاء مستخدم جديد

```bash
POST /api/users
Content-Type: application/json

{{
    "name": "أحمد محمد",
    "email": "ahmed@example.com"
}}
```

**Response:**
```json
{{
    "success": true,
    "message": "User created successfully",
    "data": {{...}}
}}
```

---

## ✅ الخطوات التالية

1. ✅ مراجعة الـ Controllers المولدة
2. ✅ إضافة قواعد Validation المناسبة
3. ✅ إضافة Middleware للمصادقة
4. ✅ إضافة Tests للـ API
5. ✅ توليد Swagger Documentation

---

{errors_section}

## 🎉 الخلاصة

تم توليد **RESTful API كامل** لـ **{self.stats['models_found']} نموذج** بنجاح!

جميع الـ endpoints جاهزة للاستخدام والتخصيص.

---

**Generated by API Generator v3.16.0**  
**SEMOP Team © 2025**
'''
        
        doc_file = self.base_path / 'API_GENERATOR_v3.16.0_REPORT.md'
        doc_file.write_text(content, encoding='utf-8')
        
        self.log('تم توليد ملف التوثيق: API_GENERATOR_v3.16.0_REPORT.md')
    
    def generate(self):
        """Run the complete generation process"""
        self.log('بدء عملية توليد API v3.16.0')
        
        # Discover models
        self.discover_models()
        
        # Generate controllers
        self.generate_controllers()
        
        # Generate routes
        self.generate_routes()
        
        # Generate documentation
        self.generate_documentation()
        
        self.log('اكتملت عملية التوليد بنجاح')
        
        return self.stats


def main():
    """Main entry point"""
    base_path = '/home/ubuntu/php-magic-system'
    
    print("=" * 60)
    print("🚀 API Generator v3.16.0")
    print("=" * 60)
    print()
    
    generator = ApiGenerator(base_path)
    stats = generator.generate()
    
    print()
    print("=" * 60)
    print("✅ اكتملت عملية التوليد بنجاح!")
    print("=" * 60)
    print()
    print(f"النماذج المكتشفة: {stats['models_found']}")
    print(f"Controllers المولدة: {stats['controllers_generated']}")
    print(f"Routes المولدة: {stats['routes_generated']}")
    print(f"الأخطاء: {len(stats['errors'])}")
    print()
    
    if stats['errors']:
        print("⚠️  الأخطاء:")
        for error in stats['errors']:
            print(f"  - {error}")
        print()
    
    print("📄 تم إنشاء تقرير التوليد: API_GENERATOR_v3.16.0_REPORT.md")
    print()


if __name__ == '__main__':
    main()
