<?php

namespace {{namespace}};

use Closure;
use Illuminate\Http\Request;

/**
 * {{name}}
 * 
 * {{description}}
 * Auto-generated by Middleware Generator v{{version}}
 * 
 * @version {{version}}
 * @date {{date}}
 * @author {{author}}
 */
class {{name}}
{
    /**
     * Supported API versions
     */
    protected array $supportedVersions = ['v1', 'v2', 'v3'];

    /**
     * Default API version
     */
    protected string $defaultVersion = 'v1';

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        // Get API version from header or URL
        $version = $this->getApiVersion($request);

        // Validate version
        if (!$this->isValidVersion($version)) {
            return response()->json([
                'success' => false,
                'message' => 'Invalid API version',
                'error' => "Version '{$version}' is not supported",
                'supported_versions' => $this->supportedVersions
            ], 400);
        }

        // Add version to request
        $request->merge(['api_version' => $version]);

        $response = $next($request);

        // Add version header to response
        return $response->header('X-API-Version', $version);
    }

    /**
     * Get API version from request
     *
     * @param Request $request
     * @return string
     */
    protected function getApiVersion(Request $request): string
    {
        // Check header first
        if ($request->hasHeader('X-API-Version')) {
            return $request->header('X-API-Version');
        }

        // Check URL path
        if (preg_match('#/(v\d+)/#', $request->path(), $matches)) {
            return $matches[1];
        }

        // Return default version
        return $this->defaultVersion;
    }

    /**
     * Check if version is valid
     *
     * @param string $version
     * @return bool
     */
    protected function isValidVersion(string $version): bool
    {
        return in_array($version, $this->supportedVersions);
    }
}
