<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Auto-Generated API Routes
|--------------------------------------------------------------------------
| Version: 3.16.0
| Generated: 2025-12-03
| Total Models: 92
|
| This file was automatically generated by API Generator v3.16.0
| DO NOT EDIT THIS FILE MANUALLY
*/


// AIApiKey API Routes
Route::prefix('ai-api-keies')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AIApiKeyApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AIApiKeyApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AIApiKeyApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AIApiKeyApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AIApiKeyApiController::class, 'destroy']);
});

// AIConversation API Routes
Route::prefix('ai-conversations')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AIConversationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AIConversationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AIConversationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AIConversationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AIConversationApiController::class, 'destroy']);
});

// AccountBalance API Routes
Route::prefix('account-balances')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AccountBalanceApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AccountBalanceApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AccountBalanceApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AccountBalanceApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AccountBalanceApiController::class, 'destroy']);
});

// AccountType API Routes
Route::prefix('account-types')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AccountTypeApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AccountTypeApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AccountTypeApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AccountTypeApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AccountTypeApiController::class, 'destroy']);
});

// AiSetting API Routes
Route::prefix('ai-settings')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AiSettingApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AiSettingApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AiSettingApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AiSettingApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AiSettingApiController::class, 'destroy']);
});

// ApiLog API Routes
Route::prefix('api-logs')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ApiLogApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ApiLogApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ApiLogApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ApiLogApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ApiLogApiController::class, 'destroy']);
});

// Attendance API Routes
Route::prefix('attendances')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AttendanceApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AttendanceApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AttendanceApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AttendanceApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AttendanceApiController::class, 'destroy']);
});

// AuditLog API Routes
Route::prefix('audit-logs')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\AuditLogApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\AuditLogApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\AuditLogApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\AuditLogApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\AuditLogApiController::class, 'destroy']);
});

// Barcode API Routes
Route::prefix('barcodes')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\BarcodeApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\BarcodeApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\BarcodeApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\BarcodeApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\BarcodeApiController::class, 'destroy']);
});

// CashBox API Routes
Route::prefix('cash-boxs')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CashBoxApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CashBoxApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CashBoxApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CashBoxApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CashBoxApiController::class, 'destroy']);
});

// ChartAccount API Routes
Route::prefix('chart-accounts')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ChartAccountApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ChartAccountApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ChartAccountApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ChartAccountApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ChartAccountApiController::class, 'destroy']);
});

// ChartGroup API Routes
Route::prefix('chart-groups')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ChartGroupApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ChartGroupApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ChartGroupApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ChartGroupApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ChartGroupApiController::class, 'destroy']);
});

// Check API Routes
Route::prefix('checks')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CheckApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CheckApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CheckApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CheckApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CheckApiController::class, 'destroy']);
});

// Client API Routes
Route::prefix('clients')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ClientApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ClientApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ClientApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ClientApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ClientApiController::class, 'destroy']);
});

// ClientGene API Routes
Route::prefix('client-genes')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ClientGeneApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ClientGeneApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ClientGeneApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ClientGeneApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ClientGeneApiController::class, 'destroy']);
});

// Configuration API Routes
Route::prefix('configurations')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ConfigurationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ConfigurationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ConfigurationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ConfigurationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ConfigurationApiController::class, 'destroy']);
});

// CostCenter API Routes
Route::prefix('cost-centers')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CostCenterApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CostCenterApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CostCenterApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CostCenterApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CostCenterApiController::class, 'destroy']);
});

// Customer API Routes
Route::prefix('customers')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CustomerApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CustomerApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CustomerApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CustomerApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CustomerApiController::class, 'destroy']);
});

// CustomerAddress API Routes
Route::prefix('customer-addresses')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CustomerAddressApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CustomerAddressApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CustomerAddressApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CustomerAddressApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CustomerAddressApiController::class, 'destroy']);
});

// CustomerCategory API Routes
Route::prefix('customer-categories')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CustomerCategoryApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CustomerCategoryApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CustomerCategoryApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CustomerCategoryApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CustomerCategoryApiController::class, 'destroy']);
});

// CustomerContact API Routes
Route::prefix('customer-contacts')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CustomerContactApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CustomerContactApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CustomerContactApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CustomerContactApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CustomerContactApiController::class, 'destroy']);
});

// Dashboard API Routes
Route::prefix('dashboards')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\DashboardApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\DashboardApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\DashboardApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\DashboardApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\DashboardApiController::class, 'destroy']);
});

// Department API Routes
Route::prefix('departments')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\DepartmentApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\DepartmentApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\DepartmentApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\DepartmentApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\DepartmentApiController::class, 'destroy']);
});

// Discount API Routes
Route::prefix('discounts')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\DiscountApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\DiscountApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\DiscountApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\DiscountApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\DiscountApiController::class, 'destroy']);
});

// DrugClassification API Routes
Route::prefix('drug-classifications')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\DrugClassificationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\DrugClassificationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\DrugClassificationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\DrugClassificationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\DrugClassificationApiController::class, 'destroy']);
});

// DrugInteraction API Routes
Route::prefix('drug-interactions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\DrugInteractionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\DrugInteractionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\DrugInteractionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\DrugInteractionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\DrugInteractionApiController::class, 'destroy']);
});

// Employee API Routes
Route::prefix('employees')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\EmployeeApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\EmployeeApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\EmployeeApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\EmployeeApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\EmployeeApiController::class, 'destroy']);
});

// EmployeeDocument API Routes
Route::prefix('employee-documents')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\EmployeeDocumentApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\EmployeeDocumentApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\EmployeeDocumentApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\EmployeeDocumentApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\EmployeeDocumentApiController::class, 'destroy']);
});

// FiscalPeriod API Routes
Route::prefix('fiscal-periods')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\FiscalPeriodApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\FiscalPeriodApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\FiscalPeriodApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\FiscalPeriodApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\FiscalPeriodApiController::class, 'destroy']);
});

// FiscalYear API Routes
Route::prefix('fiscal-years')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\FiscalYearApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\FiscalYearApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\FiscalYearApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\FiscalYearApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\FiscalYearApiController::class, 'destroy']);
});

// Gene API Routes
Route::prefix('genes')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\GeneApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\GeneApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\GeneApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\GeneApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\GeneApiController::class, 'destroy']);
});

// GeneActivation API Routes
Route::prefix('gene-activations')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\GeneActivationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\GeneActivationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\GeneActivationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\GeneActivationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\GeneActivationApiController::class, 'destroy']);
});

// GeneFeature API Routes
Route::prefix('gene-features')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\GeneFeatureApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\GeneFeatureApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\GeneFeatureApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\GeneFeatureApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\GeneFeatureApiController::class, 'destroy']);
});

// Holding API Routes
Route::prefix('holdings')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\HoldingApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\HoldingApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\HoldingApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\HoldingApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\HoldingApiController::class, 'destroy']);
});

// HoldingSector API Routes
Route::prefix('holding-sectors')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\HoldingSectorApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\HoldingSectorApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\HoldingSectorApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\HoldingSectorApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\HoldingSectorApiController::class, 'destroy']);
});

// InsurancePolicy API Routes
Route::prefix('insurance-policies')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\InsurancePolicyApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\InsurancePolicyApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\InsurancePolicyApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\InsurancePolicyApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\InsurancePolicyApiController::class, 'destroy']);
});

// Item API Routes
Route::prefix('items')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ItemApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ItemApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ItemApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ItemApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ItemApiController::class, 'destroy']);
});

// ItemCategory API Routes
Route::prefix('item-categories')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ItemCategoryApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ItemCategoryApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ItemCategoryApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ItemCategoryApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ItemCategoryApiController::class, 'destroy']);
});

// JournalEntry API Routes
Route::prefix('journal-entries')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\JournalEntryApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\JournalEntryApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\JournalEntryApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\JournalEntryApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\JournalEntryApiController::class, 'destroy']);
});

// JournalEntryDetail API Routes
Route::prefix('journal-entry-details')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\JournalEntryDetailApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\JournalEntryDetailApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\JournalEntryDetailApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\JournalEntryDetailApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\JournalEntryDetailApiController::class, 'destroy']);
});

// JournalEntryLine API Routes
Route::prefix('journal-entry-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\JournalEntryLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\JournalEntryLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\JournalEntryLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\JournalEntryLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\JournalEntryLineApiController::class, 'destroy']);
});

// LatitudePoint API Routes
Route::prefix('latitude-points')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\LatitudePointApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\LatitudePointApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\LatitudePointApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\LatitudePointApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\LatitudePointApiController::class, 'destroy']);
});

// Leave API Routes
Route::prefix('leaves')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\LeaveApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\LeaveApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\LeaveApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\LeaveApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\LeaveApiController::class, 'destroy']);
});

// LoyaltyPoint API Routes
Route::prefix('loyalty-points')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\LoyaltyPointApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\LoyaltyPointApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\LoyaltyPointApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\LoyaltyPointApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\LoyaltyPointApiController::class, 'destroy']);
});

// ManusTransaction API Routes
Route::prefix('manus-transactions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ManusTransactionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ManusTransactionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ManusTransactionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ManusTransactionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ManusTransactionApiController::class, 'destroy']);
});

// ManusUsageStat API Routes
Route::prefix('manus-usage-stats')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ManusUsageStatApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ManusUsageStatApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ManusUsageStatApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ManusUsageStatApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ManusUsageStatApiController::class, 'destroy']);
});

// ManusWebhook API Routes
Route::prefix('manus-webhooks')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ManusWebhookApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ManusWebhookApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ManusWebhookApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ManusWebhookApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ManusWebhookApiController::class, 'destroy']);
});

// MedicalInsurance API Routes
Route::prefix('medical-insurances')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\MedicalInsuranceApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\MedicalInsuranceApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\MedicalInsuranceApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\MedicalInsuranceApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\MedicalInsuranceApiController::class, 'destroy']);
});

// Notification API Routes
Route::prefix('notifications')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\NotificationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\NotificationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\NotificationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\NotificationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\NotificationApiController::class, 'destroy']);
});

// Organization API Routes
Route::prefix('organizations')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\OrganizationApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\OrganizationApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\OrganizationApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\OrganizationApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\OrganizationApiController::class, 'destroy']);
});

// OrganizationGene API Routes
Route::prefix('organization-genes')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\OrganizationGeneApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\OrganizationGeneApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\OrganizationGeneApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\OrganizationGeneApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\OrganizationGeneApiController::class, 'destroy']);
});

// PaymentMethod API Routes
Route::prefix('payment-methods')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PaymentMethodApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PaymentMethodApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PaymentMethodApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PaymentMethodApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PaymentMethodApiController::class, 'destroy']);
});

// Payroll API Routes
Route::prefix('payrolls')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PayrollApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PayrollApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PayrollApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PayrollApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PayrollApiController::class, 'destroy']);
});

// Permission API Routes
Route::prefix('permissions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PermissionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PermissionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PermissionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PermissionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PermissionApiController::class, 'destroy']);
});

// Prescription API Routes
Route::prefix('prescriptions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PrescriptionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PrescriptionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PrescriptionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PrescriptionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PrescriptionApiController::class, 'destroy']);
});

// Project API Routes
Route::prefix('projects')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ProjectApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ProjectApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ProjectApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ProjectApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ProjectApiController::class, 'destroy']);
});

// Promotion API Routes
Route::prefix('promotions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PromotionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PromotionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PromotionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PromotionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PromotionApiController::class, 'destroy']);
});

// PurchaseInvoice API Routes
Route::prefix('purchase-invoices')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseInvoiceApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseInvoiceApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceApiController::class, 'destroy']);
});

// PurchaseInvoiceLine API Routes
Route::prefix('purchase-invoice-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseInvoiceLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseInvoiceLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseInvoiceLineApiController::class, 'destroy']);
});

// PurchaseOrder API Routes
Route::prefix('purchase-orders')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseOrderApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseOrderApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseOrderApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseOrderApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseOrderApiController::class, 'destroy']);
});

// PurchaseOrderLine API Routes
Route::prefix('purchase-order-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseOrderLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseOrderLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseOrderLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseOrderLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseOrderLineApiController::class, 'destroy']);
});

// PurchaseReturn API Routes
Route::prefix('purchase-returns')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseReturnApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseReturnApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseReturnApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseReturnApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseReturnApiController::class, 'destroy']);
});

// PurchaseReturnLine API Routes
Route::prefix('purchase-return-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\PurchaseReturnLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\PurchaseReturnLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\PurchaseReturnLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\PurchaseReturnLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\PurchaseReturnLineApiController::class, 'destroy']);
});

// Report API Routes
Route::prefix('reports')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\ReportApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\ReportApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\ReportApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\ReportApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\ReportApiController::class, 'destroy']);
});

// Role API Routes
Route::prefix('roles')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\RoleApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\RoleApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\RoleApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\RoleApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\RoleApiController::class, 'destroy']);
});

// RolePermission API Routes
Route::prefix('role-permissions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\RolePermissionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\RolePermissionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\RolePermissionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\RolePermissionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\RolePermissionApiController::class, 'destroy']);
});

// SalesInvoice API Routes
Route::prefix('sales-invoices')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesInvoiceApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesInvoiceApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesInvoiceApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesInvoiceApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesInvoiceApiController::class, 'destroy']);
});

// SalesInvoiceLine API Routes
Route::prefix('sales-invoice-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesInvoiceLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesInvoiceLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesInvoiceLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesInvoiceLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesInvoiceLineApiController::class, 'destroy']);
});

// SalesOrder API Routes
Route::prefix('sales-orders')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesOrderApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesOrderApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesOrderApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesOrderApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesOrderApiController::class, 'destroy']);
});

// SalesOrderLine API Routes
Route::prefix('sales-order-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesOrderLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesOrderLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesOrderLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesOrderLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesOrderLineApiController::class, 'destroy']);
});

// SalesReturn API Routes
Route::prefix('sales-returns')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesReturnApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesReturnApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesReturnApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesReturnApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesReturnApiController::class, 'destroy']);
});

// SalesReturnLine API Routes
Route::prefix('sales-return-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SalesReturnLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SalesReturnLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SalesReturnLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SalesReturnLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SalesReturnLineApiController::class, 'destroy']);
});

// Sector API Routes
Route::prefix('sectors')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SectorApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SectorApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SectorApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SectorApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SectorApiController::class, 'destroy']);
});

// Setting API Routes
Route::prefix('settings')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SettingApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SettingApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SettingApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SettingApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SettingApiController::class, 'destroy']);
});

// StockCount API Routes
Route::prefix('stock-counts')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\StockCountApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\StockCountApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\StockCountApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\StockCountApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\StockCountApiController::class, 'destroy']);
});

// StockCountLine API Routes
Route::prefix('stock-count-lines')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\StockCountLineApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\StockCountLineApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\StockCountLineApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\StockCountLineApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\StockCountLineApiController::class, 'destroy']);
});

// StockLevel API Routes
Route::prefix('stock-levels')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\StockLevelApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\StockLevelApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\StockLevelApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\StockLevelApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\StockLevelApiController::class, 'destroy']);
});

// StockMovement API Routes
Route::prefix('stock-movements')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\StockMovementApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\StockMovementApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\StockMovementApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\StockMovementApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\StockMovementApiController::class, 'destroy']);
});

// Supplier API Routes
Route::prefix('suppliers')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SupplierApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SupplierApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SupplierApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SupplierApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SupplierApiController::class, 'destroy']);
});

// SupplierAddress API Routes
Route::prefix('supplier-addresses')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SupplierAddressApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SupplierAddressApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SupplierAddressApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SupplierAddressApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SupplierAddressApiController::class, 'destroy']);
});

// SupplierCategory API Routes
Route::prefix('supplier-categories')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SupplierCategoryApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SupplierCategoryApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SupplierCategoryApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SupplierCategoryApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SupplierCategoryApiController::class, 'destroy']);
});

// SupplierContact API Routes
Route::prefix('supplier-contacts')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\SupplierContactApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\SupplierContactApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\SupplierContactApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\SupplierContactApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\SupplierContactApiController::class, 'destroy']);
});

// Task API Routes
Route::prefix('tasks')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\TaskApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\TaskApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\TaskApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\TaskApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\TaskApiController::class, 'destroy']);
});

// Transaction API Routes
Route::prefix('transactions')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\TransactionApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\TransactionApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\TransactionApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\TransactionApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\TransactionApiController::class, 'destroy']);
});

// Unit API Routes
Route::prefix('units')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\UnitApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\UnitApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\UnitApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\UnitApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\UnitApiController::class, 'destroy']);
});

// UnitSetting API Routes
Route::prefix('unit-settings')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\UnitSettingApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\UnitSettingApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\UnitSettingApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\UnitSettingApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\UnitSettingApiController::class, 'destroy']);
});

// User API Routes
Route::prefix('users')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\UserApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\UserApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\UserApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\UserApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\UserApiController::class, 'destroy']);
});

// UserRole API Routes
Route::prefix('user-roles')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\UserRoleApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\UserRoleApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\UserRoleApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\UserRoleApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\UserRoleApiController::class, 'destroy']);
});

// Vault API Routes
Route::prefix('vaults')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\VaultApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\VaultApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\VaultApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\VaultApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\VaultApiController::class, 'destroy']);
});

// Warehouse API Routes
Route::prefix('warehouses')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\WarehouseApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\WarehouseApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\WarehouseApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\WarehouseApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\WarehouseApiController::class, 'destroy']);
});

// WeightedItem API Routes
Route::prefix('weighted-items')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\WeightedItemApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\WeightedItemApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\WeightedItemApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\WeightedItemApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\WeightedItemApiController::class, 'destroy']);
});

// Cashier API Routes
Route::prefix('cashiers')->group(function () {
    Route::get('/', [App\Http\Controllers\Api\CashierApiController::class, 'index']);
    Route::post('/', [App\Http\Controllers\Api\CashierApiController::class, 'store']);
    Route::get('/{id}', [App\Http\Controllers\Api\CashierApiController::class, 'show']);
    Route::put('/{id}', [App\Http\Controllers\Api\CashierApiController::class, 'update']);
    Route::delete('/{id}', [App\Http\Controllers\Api\CashierApiController::class, 'destroy']);
});
